import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { api } from '../api';
type Row=Record<string,any>;
const names:Record<string,string>={categories:'التصنيفات',brands:'العلامات التجارية',attributes:'الخصائص',filters:'الفلاتر'};
const empty={id:'',nameAr:'',nameEn:'',slug:'',descriptionAr:'',descriptionEn:'',parentId:'',attributeIds:[] as string[],assetUrl:'',sortOrder:0,isActive:true,inputType:'select',filterType:'option',isFilterable:true,seoTitleAr:'',seoTitleEn:'',seoDescriptionAr:'',seoDescriptionEn:''};
function Field({label,value,onChange,type='text'}:{label:string;value:any;onChange:(value:string)=>void;type?:string}){return <label className="field"><span>{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function unavailableCategoryParents(categories:Row[],categoryId:string):Set<string>{
  const unavailable=new Set<string>();if(!categoryId)return unavailable;const pending=[categoryId];
  while(pending.length){const current=pending.pop()!;if(unavailable.has(current))continue;unavailable.add(current);
    for(const category of categories)if(category.parent_id===current)pending.push(category.id);}
  return unavailable;
}

export function CatalogManager({kind,canWrite=true}:{kind:string;canWrite?:boolean}){
  const[data,setData]=useState<Row[]>([]),[media,setMedia]=useState<Row[]>([]),[attributes,setAttributes]=useState<Row[]>([]),[editing,setEditing]=useState<Row|null>(null),[valuesFor,setValuesFor]=useState<Row|null>(null);
  const[loading,setLoading]=useState(true),[error,setError]=useState('');
  const load=useCallback(async()=>{setLoading(true);try{setData(await api<Row[]>('/admin/catalog/'+kind));}catch(value){setError((value as Error).message);}finally{setLoading(false);}},[kind]);
  useEffect(()=>{void load();api<Row[]>('/admin/media').then(setMedia).catch(()=>setMedia([]));if(kind==='categories')api<Row[]>('/admin/catalog/attributes').then(setAttributes).catch(()=>setAttributes([]));},[kind,load]);
  const start=(row?:Row)=>setEditing(row?{...empty,id:row.id,nameAr:row.title_ar??row.name_ar??'',nameEn:row.title_en??row.name_en??'',slug:row.slug,
    descriptionAr:row.description_ar??'',descriptionEn:row.description_en??'',parentId:row.parent_id??'',attributeIds:row.attribute_ids??[],assetUrl:row.image_url??row.logo_url??'',sortOrder:row.sort_order??0,
    isActive:row.is_active??true,inputType:row.input_type??'select',filterType:row.filter_type??'option',isFilterable:row.is_filterable??true,
    seoTitleAr:row.seo_title_ar??'',seoTitleEn:row.seo_title_en??'',seoDescriptionAr:row.seo_description_ar??'',seoDescriptionEn:row.seo_description_en??''}:{...empty});
  const remove=async(row:Row)=>{if(!window.confirm(`حذف «${row.title_ar??row.name_ar}»؟`))return;try{await api('/admin/catalog/'+kind+'/'+row.id,{method:'DELETE'});await load();}catch(value){setError((value as Error).message);}};
  const toggle=async(row:Row)=>{try{await api('/admin/catalog/'+kind+'/'+row.id,{method:'PATCH',body:JSON.stringify({isActive:!(row.is_active??true)})});await load();}catch(value){setError((value as Error).message);}};
  return <><div className="page-head"><div><h1>{names[kind]??kind}</h1><p>إدارة كاملة للبيانات والترتيب والحالة والقيم.</p></div>{canWrite&&<button className="button" onClick={()=>start()}>إضافة</button>}</div>{error&&<div className="error">{error}</div>}
    <div className="table-wrap">{loading?<div className="empty">جارٍ التحميل…</div>:<table><thead><tr><th>الاسم</th><th>الرابط</th>{kind==='categories'&&<th>التصنيف الأب</th>}<th>الترتيب</th><th>الحالة</th>{canWrite&&<th>الإجراءات</th>}</tr></thead><tbody>{data.map(row=><tr key={row.id}><td><strong>{row.title_ar??row.name_ar}</strong><div className="muted">{row.title_en??row.name_en}</div></td><td>{row.slug}</td>{kind==='categories'&&<td>{data.find(parent=>parent.id===row.parent_id)?.title_ar??'—'}</td>}<td>{row.sort_order}</td><td><span className="badge">{row.is_active===false?'متوقف':'فعّال'}</span></td>{canWrite&&<td><div className="mini-actions"><button onClick={()=>start(row)}>تعديل</button><button onClick={()=>void toggle(row)}>{row.is_active===false?'تفعيل':'تعطيل'}</button>{['attributes','filters'].includes(kind)&&<button onClick={()=>setValuesFor(row)}>القيم ({row.values?.length??0})</button>}<button className="danger-text" onClick={()=>void remove(row)}>حذف</button></div></td>}</tr>)}</tbody></table>}</div>
    {editing&&<CatalogDialog kind={kind} form={editing} categories={data} attributes={attributes} media={media} close={()=>setEditing(null)} saved={async()=>{setEditing(null);await load();}}/>}
    {valuesFor&&<ValuesDialog kind={kind} entry={valuesFor} close={()=>setValuesFor(null)} saved={async()=>{await load();const updated=(await api<Row[]>('/admin/catalog/'+kind)).find(row=>row.id===valuesFor.id);setValuesFor(updated??null);}}/>}</>;
}

function CatalogDialog({kind,form:initial,categories,attributes,media,close,saved}:{kind:string;form:Row;categories:Row[];attributes:Row[];media:Row[];close:()=>void;saved:()=>Promise<void>}){
  const[form,setForm]=useState(initial),[error,setError]=useState(''),[showMedia,setShowMedia]=useState(false);const change=(key:string,value:any)=>setForm((current:Row)=>({...current,[key]:value}));
  const blockedParentIds=unavailableCategoryParents(categories,form.id);
  const submit=async(event:FormEvent)=>{event.preventDefault();const titleKind=kind==='categories'||kind==='brands';const body:any={slug:form.slug,sortOrder:Number(form.sortOrder),
    ...(titleKind?{titleAr:form.nameAr,titleEn:form.nameEn||undefined,descriptionAr:form.descriptionAr.trim()||null,descriptionEn:form.descriptionEn.trim()||null}:{nameAr:form.nameAr,nameEn:form.nameEn||undefined}),
    ...(kind==='categories'?{parentId:form.parentId||null,imageUrl:form.assetUrl.trim()||null}:kind==='brands'?{logoUrl:form.assetUrl.trim()||null}:{}),
    ...(kind==='attributes'?{inputType:form.inputType,isFilterable:form.isFilterable}:{isActive:form.isActive}),...(kind==='filters'?{filterType:form.filterType}:{}),
    ...(['categories','brands'].includes(kind)?{seoTitleAr:form.seoTitleAr.trim()||null,seoTitleEn:form.seoTitleEn.trim()||null,seoDescriptionAr:form.seoDescriptionAr.trim()||null,seoDescriptionEn:form.seoDescriptionEn.trim()||null}:{}),
    ...(['categories','brands'].includes(kind)?{isActive:form.isActive}:{})};
    try{const result=await api<Row>('/admin/catalog/'+kind+(form.id?'/'+form.id:''),{method:form.id?'PATCH':'POST',body:JSON.stringify(body)});
      if(kind==='categories')await api(`/admin/catalog/categories/${result.id}/attributes`,{method:'PATCH',body:JSON.stringify({attributeIds:form.attributeIds})});await saved();}catch(value){setError((value as Error).message);}};
  return <div className="dialog-backdrop"><form className="dialog catalog-dialog" onSubmit={submit}><div className="dialog-head"><h2>{form.id?'تعديل':'إضافة'} {names[kind]}</h2><button type="button" className="close" onClick={close}>×</button></div>{error&&<div className="error">{error}</div>}<div className="form-grid"><Field label="الاسم بالعربية" value={form.nameAr} onChange={v=>change('nameAr',v)}/><Field label="الاسم بالإنجليزية" value={form.nameEn} onChange={v=>change('nameEn',v)}/><Field label="الرابط المختصر" value={form.slug} onChange={v=>change('slug',v)}/><Field label="الترتيب" type="number" value={form.sortOrder} onChange={v=>change('sortOrder',v)}/>
    {kind==='categories'&&<><label className="field"><span>التصنيف الأب</span><select value={form.parentId} onChange={e=>change('parentId',e.target.value)}><option value="">بدون أب</option>{categories.filter(row=>!blockedParentIds.has(row.id)).map(row=><option key={row.id} value={row.id}>{row.title_ar}</option>)}</select></label><fieldset className="choice-list"><legend>خصائص التصنيف</legend>{attributes.map(attribute=><label key={attribute.id}><input type="checkbox" checked={form.attributeIds.includes(attribute.id)} onChange={e=>change('attributeIds',e.target.checked?[...form.attributeIds,attribute.id]:form.attributeIds.filter((id:string)=>id!==attribute.id))}/>{attribute.name_ar}</label>)}</fieldset></>}
    {kind==='attributes'&&<label className="field"><span>نوع الإدخال</span><select value={form.inputType} onChange={e=>change('inputType',e.target.value)}><option value="select">اختيار</option><option value="text">نص</option><option value="number">رقم</option><option value="color">لون</option></select></label>}{kind==='filters'&&<label className="field"><span>نوع الفلتر</span><select value={form.filterType} onChange={e=>change('filterType',e.target.value)}><option value="option">قيم اختيار</option><option value="range">Range رقمي</option></select></label>}
    {['categories','brands'].includes(kind)&&<><label className="field full"><span>الوصف بالعربية</span><textarea rows={3} value={form.descriptionAr} onChange={e=>change('descriptionAr',e.target.value)}/></label><label className="field full"><span>الوصف بالإنجليزية</span><textarea dir="ltr" rows={3} value={form.descriptionEn} onChange={e=>change('descriptionEn',e.target.value)}/></label><div className="field full"><span>{kind==='categories'?'صورة التصنيف':'شعار العلامة'}</span><div className="asset-field">{form.assetUrl&&<img src={form.assetUrl} alt=""/>}<input value={form.assetUrl} onChange={e=>change('assetUrl',e.target.value)} placeholder="رابط الصورة"/><button type="button" className="button secondary" onClick={()=>setShowMedia(true)}>مكتبة الوسائط</button>{form.assetUrl&&<button type="button" className="danger-text" onClick={()=>change('assetUrl','')}>إزالة</button>}</div></div><Field label="عنوان SEO بالعربية" value={form.seoTitleAr} onChange={v=>change('seoTitleAr',v)}/><Field label="SEO title English" value={form.seoTitleEn} onChange={v=>change('seoTitleEn',v)}/><label className="field"><span>وصف SEO بالعربية</span><textarea rows={3} value={form.seoDescriptionAr} onChange={e=>change('seoDescriptionAr',e.target.value)}/></label><label className="field"><span>SEO description English</span><textarea rows={3} dir="ltr" value={form.seoDescriptionEn} onChange={e=>change('seoDescriptionEn',e.target.value)}/></label></>}
    <label className="field check"><input type="checkbox" checked={form.isActive} onChange={e=>change('isActive',e.target.checked)}/> فعّال</label>{kind==='attributes'&&<label className="field check"><input type="checkbox" checked={form.isFilterable} onChange={e=>change('isFilterable',e.target.checked)}/> قابل للفلترة</label>}</div><div className="dialog-actions"><button className="button">حفظ</button><button type="button" className="button secondary" onClick={close}>إلغاء</button></div>
    {showMedia&&<div className="nested-dialog"><div className="media-picker"><div className="dialog-head"><h3>اختر صورة</h3><button type="button" className="close" onClick={()=>setShowMedia(false)}>×</button></div><div className="media-picker-grid">{media.filter(row=>row.mime_type?.startsWith('image/')).map(row=><button type="button" key={row.id} onClick={()=>{change('assetUrl',row.public_url);setShowMedia(false);}}><img src={row.public_url} alt=""/><span>اختيار</span></button>)}</div></div></div>}
  </form></div>;
}

function ValuesDialog({kind,entry,close,saved}:{kind:string;entry:Row;close:()=>void;saved:()=>Promise<void>}){
  const[editing,setEditing]=useState<Row|null>(null),[error,setError]=useState('');const values=entry.values??[];
  const save=async(event:FormEvent)=>{event.preventDefault();if(!editing)return;try{await api(`/admin/catalog/${kind}/${entry.id}/values${editing.id?'/'+editing.id:''}`,{method:editing.id?'PATCH':'POST',body:JSON.stringify({valueAr:editing.valueAr,valueEn:editing.valueEn||undefined,code:editing.code||undefined,sortOrder:Number(editing.sortOrder??0)})});setEditing(null);await saved();}catch(value){setError((value as Error).message);}};
  const remove=async(valueId:string)=>{if(!window.confirm('حذف القيمة؟'))return;try{await api(`/admin/catalog/${kind}/${entry.id}/values/${valueId}`,{method:'DELETE'});await saved();}catch(value){setError((value as Error).message);}};
  return <div className="dialog-backdrop"><div className="dialog values-dialog"><div className="dialog-head"><h2>قيم: {entry.name_ar}</h2><button className="close" onClick={close}>×</button></div>{error&&<div className="error">{error}</div>}<button className="button" onClick={()=>setEditing({valueAr:'',valueEn:'',code:'',sortOrder:values.length})}>إضافة قيمة</button><div className="value-list">{values.map((value:Row)=><div key={value.id}><span><strong>{value.value_ar}</strong> <small>{value.value_en}</small></span><span>{value.code}</span><div className="mini-actions"><button onClick={()=>setEditing({id:value.id,valueAr:value.value_ar,valueEn:value.value_en??'',code:value.code??'',sortOrder:value.sort_order})}>تعديل</button><button className="danger-text" onClick={()=>void remove(value.id)}>حذف</button></div></div>)}</div>{editing&&<form className="panel" onSubmit={save}><div className="form-grid"><Field label="القيمة بالعربية" value={editing.valueAr} onChange={v=>setEditing(current=>({...current!,valueAr:v}))}/><Field label="القيمة بالإنجليزية" value={editing.valueEn} onChange={v=>setEditing(current=>({...current!,valueEn:v}))}/>{kind==='attributes'&&<Field label="الكود" value={editing.code} onChange={v=>setEditing(current=>({...current!,code:v}))}/>}<Field label="الترتيب" type="number" value={editing.sortOrder} onChange={v=>setEditing(current=>({...current!,sortOrder:v}))}/></div><div className="dialog-actions"><button className="button">حفظ القيمة</button><button type="button" className="button secondary" onClick={()=>setEditing(null)}>إلغاء</button></div></form>}</div></div>;
}
