import { useEffect, useMemo, useState, type DragEvent, type FormEvent } from 'react';
import { api } from '../api';

type Row=Record<string,any>;
type Spec={key:string;value:string};
type Image={mediaAssetId?:string;imageUrl:string;altTextAr:string;altTextEn:string;isPrimary:boolean;sortOrder:number};
type Variant={id?:string;titleAr:string;titleEn:string;sku:string;barcode:string;attributeValueIds:string[];isDefault:boolean;isActive:boolean;sortOrder:number};
const emptyVariant=():Variant=>({titleAr:'',titleEn:'',sku:'',barcode:'',attributeValueIds:[],isDefault:false,isActive:true,sortOrder:0});
const units:Record<string,string>={piece:'قطعة',box:'صندوق',carton:'كرتون',meter:'متر',kilogram:'كيلوجرام',gram:'جرام',liter:'لتر',set:'طقم',roll:'لفة',pack:'عبوة'};

function Field({label,value,onChange,required,type='text',step,placeholder}:{label:string;value:any;onChange:(value:string)=>void;required?:boolean;type?:string;step?:string;placeholder?:string}){
  return <label className="field"><span>{label}</span><input type={type} step={step} required={required} value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/></label>;
}
function CheckList({items,selected,onChange,label}:{items:Row[];selected:string[];onChange:(ids:string[])=>void;label:string}){
  return <fieldset className="choice-list"><legend>{label}</legend>{items.map(item=><label key={item.id}><input type="checkbox" checked={selected.includes(item.id)}
    onChange={e=>onChange(e.target.checked?[...selected,item.id]:selected.filter(id=>id!==item.id))}/>{item.title_ar??item.name_ar}</label>)}</fieldset>;
}

export function ProductEditor({product,close,saved}:{product:Row;close:()=>void;saved:()=>Promise<void>}){
  const[lookups,setLookups]=useState<{categories:Row[];brands:Row[];attributes:Row[];filters:Row[];media:Row[];products:Row[]}>({categories:[],brands:[],attributes:[],filters:[],media:[],products:[]});
  const[error,setError]=useState(''),[saving,setSaving]=useState(false),[mediaOpen,setMediaOpen]=useState(false),[dragIndex,setDragIndex]=useState<number|null>(null);
  const[form,setForm]=useState(()=>({
    titleAr:product.title_ar??'',titleEn:product.title_en??'',slug:product.slug??'',categoryId:product.category_id??'',brandId:product.brand_id??'',
    sku:product.sku??'',barcode:product.barcode??'',modelCode:product.model_code??'',youtubeUrl:product.youtube_url??'',tags:(product.tags??[]).join(', '),
    status:product.status??'draft',availabilityStatus:product.availability_status??'available',unitOfMeasure:product.unit_of_measure??'piece',
    minimumRequestQuantity:Number(product.minimum_request_quantity??1),maximumRequestQuantity:product.maximum_request_quantity??'',quantityStep:Number(product.quantity_step??1),
    sortOrder:Number(product.sort_order??0),quoteEnabled:product.quote_enabled??true,isFeatured:product.is_featured??false,
    shortDescriptionAr:product.short_description_ar??'',shortDescriptionEn:product.short_description_en??'',
    detailedDescriptionAr:product.detailed_description_ar??'',detailedDescriptionEn:product.detailed_description_en??'',
    seoTitleAr:product.seo_title_ar??'',seoTitleEn:product.seo_title_en??'',seoDescriptionAr:product.seo_description_ar??'',seoDescriptionEn:product.seo_description_en??'',
    extraCategoryIds:product.extra_category_ids??[],relatedProductIds:product.related_product_ids??[],filterValueIds:product.filter_value_ids??[],
    filterRanges:(product.filter_ranges??[]).map((r:Row)=>({filterId:r.filterId??r.filterid,value:Number(r.value)}))
  }));
  const[specs,setSpecs]=useState<Spec[]>(()=>Object.entries(product.specifications??{}).map(([key,value])=>({key,value:String(value)})));
  const[images,setImages]=useState<Image[]>(()=>(product.images??[]).map((item:Row,index:number)=>({mediaAssetId:item.media_asset_id,imageUrl:item.image_url,
    altTextAr:item.alt_text_ar??'',altTextEn:item.alt_text_en??'',isPrimary:item.is_primary??index===0,sortOrder:index})));
  const[variants,setVariants]=useState<Variant[]>(()=>(product.variants??[]).map((item:Row,index:number)=>({id:item.id,titleAr:item.title_ar,titleEn:item.title_en??'',sku:item.sku??'',
    barcode:item.barcode??'',attributeValueIds:item.attribute_value_ids??[],isDefault:item.is_default,isActive:item.is_active,sortOrder:index})));
  useEffect(()=>{Promise.all([
    api<Row[]>('/admin/catalog/categories'),api<Row[]>('/admin/catalog/brands'),api<Row[]>('/admin/catalog/attributes'),api<Row[]>('/admin/catalog/filters'),
    api<Row[]>('/admin/media'),api<{items:Row[]}>('/admin/products?pageSize=100')
  ]).then(([categories,brands,attributes,filters,media,products])=>setLookups({categories,brands,attributes,filters,media,products:products.items.filter(p=>p.id!==product.id)}))
    .catch(value=>setError((value as Error).message));},[product.id]);
  const change=(key:string,value:any)=>setForm(current=>({...current,[key]:value}));
  const optionFilters=lookups.filters.filter(filter=>filter.filter_type==='option');
  const rangeFilters=lookups.filters.filter(filter=>filter.filter_type==='range');
  const categoryAttributeIds=lookups.categories.find(category=>category.id===form.categoryId)?.attribute_ids??[];
  const availableAttributes=categoryAttributeIds.length?lookups.attributes.filter(attribute=>categoryAttributeIds.includes(attribute.id)):lookups.attributes;
  const filterValues=useMemo(()=>optionFilters.flatMap(filter=>(filter.values??[]).map((value:Row)=>({...value,group:filter.name_ar}))),[optionFilters]);
  const updateImage=(index:number,patch:Partial<Image>)=>setImages(current=>current.map((item,i)=>i===index?{...item,...patch}:item));
  const setPrimary=(index:number)=>setImages(current=>current.map((item,i)=>({...item,isPrimary:i===index})));
  const addMedia=(asset:Row)=>{if(images.some(image=>image.mediaAssetId===asset.id))return;setImages(current=>[...current,{mediaAssetId:asset.id,imageUrl:asset.public_url,
    altTextAr:'',altTextEn:'',isPrimary:current.length===0,sortOrder:current.length}]);};
  const reorder=(from:number,to:number)=>{if(to<0||to>=images.length||from===to)return;setImages(current=>{const copy=[...current];const[item]=copy.splice(from,1);if(!item)return current;copy.splice(to,0,item);
    return copy.map((image,index)=>({...image,sortOrder:index}));});};
  const drop=(event:DragEvent,index:number)=>{event.preventDefault();if(dragIndex!==null)reorder(dragIndex,index);setDragIndex(null);};
  const updateVariant=(index:number,patch:Partial<Variant>)=>setVariants(current=>current.map((item,i)=>i===index?{...item,...patch}:item));
  const setDefaultVariant=(index:number)=>setVariants(current=>current.map((item,i)=>({...item,isDefault:i===index})));
  const selectAttribute=(variantIndex:number,attribute:Row,valueId:string)=>{const variant=variants[variantIndex];if(!variant)return;const valueIds=new Set((variant.attributeValueIds??[]).filter(id=>!(attribute.values??[]).some((v:Row)=>v.id===id)));
    if(valueId)valueIds.add(valueId);updateVariant(variantIndex,{attributeValueIds:[...valueIds]});};
  const submit=async(event:FormEvent)=>{event.preventDefault();setError('');setSaving(true);try{
    const nullable=(value:unknown)=>value===''?null:value;const body={...form,categoryId:form.categoryId||null,brandId:form.brandId||null,
      titleEn:nullable(form.titleEn),shortDescriptionAr:nullable(form.shortDescriptionAr),shortDescriptionEn:nullable(form.shortDescriptionEn),
      detailedDescriptionAr:nullable(form.detailedDescriptionAr),detailedDescriptionEn:nullable(form.detailedDescriptionEn),modelCode:nullable(form.modelCode),
      sku:nullable(form.sku),barcode:nullable(form.barcode),youtubeUrl:nullable(form.youtubeUrl),seoTitleAr:nullable(form.seoTitleAr),seoTitleEn:nullable(form.seoTitleEn),
      seoDescriptionAr:nullable(form.seoDescriptionAr),seoDescriptionEn:nullable(form.seoDescriptionEn),
      maximumRequestQuantity:form.maximumRequestQuantity===''?(product.id?null:undefined):Number(form.maximumRequestQuantity),tags:String(form.tags).split(',').map((v:string)=>v.trim()).filter(Boolean),
      specifications:Object.fromEntries(specs.filter(item=>item.key.trim()).map(item=>[item.key.trim(),item.value])),
      images:images.map((image,index)=>({...image,sortOrder:index})),variants:variants.map((variant,index)=>({...variant,titleEn:nullable(variant.titleEn),sku:nullable(variant.sku),barcode:nullable(variant.barcode),sortOrder:index})),
      filterRanges:form.filterRanges.filter((range:Row)=>Number.isFinite(Number(range.value))).map((range:Row)=>({...range,value:Number(range.value)}))};
    await api(product.id?'/admin/products/'+product.id:'/admin/products',{method:product.id?'PATCH':'POST',body:JSON.stringify(body)});await saved();
  }catch(value){setError((value as Error).message);}finally{setSaving(false);}};
  return <div className="dialog-backdrop"><form className="dialog product-dialog" onSubmit={submit}><div className="dialog-head"><div><h2>{product.id?'تعديل المنتج':'منتج جديد'}</h2><p className="muted">أدر كل بيانات الكتالوج من مكان واحد</p></div><button type="button" className="close" onClick={close}>×</button></div>
    {error&&<div className="error">{error}</div>}
    <section className="editor-section"><h3>البيانات الأساسية</h3><div className="form-grid">
      <Field label="الاسم بالعربية" value={form.titleAr} onChange={v=>change('titleAr',v)} required/><Field label="الاسم بالإنجليزية" value={form.titleEn} onChange={v=>change('titleEn',v)}/>
      <Field label="الرابط المختصر" value={form.slug} onChange={v=>change('slug',v)} required/><label className="field"><span>التصنيف الرئيسي</span><select value={form.categoryId} onChange={e=>change('categoryId',e.target.value)}><option value="">بدون تصنيف</option>{lookups.categories.map(row=><option key={row.id} value={row.id}>{row.title_ar}</option>)}</select></label>
      <label className="field"><span>العلامة التجارية</span><select value={form.brandId} onChange={e=>change('brandId',e.target.value)}><option value="">بدون علامة</option>{lookups.brands.map(row=><option key={row.id} value={row.id}>{row.title_ar}</option>)}</select></label>
      <Field label="SKU" value={form.sku} onChange={v=>change('sku',v)}/><Field label="Barcode" value={form.barcode} onChange={v=>change('barcode',v)}/><Field label="الموديل" value={form.modelCode} onChange={v=>change('modelCode',v)}/>
      <Field label="رابط YouTube" type="url" value={form.youtubeUrl} onChange={v=>change('youtubeUrl',v)} placeholder="https://youtube.com/..."/><Field label="Tags (افصل بفاصلة)" value={form.tags} onChange={v=>change('tags',v)}/>
      <label className="field"><span>الحالة</span><select value={form.status} onChange={e=>change('status',e.target.value)}><option value="draft">مسودة</option><option value="published">منشور</option><option value="archived">مؤرشف</option></select></label>
      <label className="field"><span>التوفر</span><select value={form.availabilityStatus} onChange={e=>change('availabilityStatus',e.target.value)}><option value="available">متاح</option><option value="on_request">حسب الطلب</option><option value="temporarily_unavailable">غير متاح مؤقتًا</option><option value="discontinued">متوقف</option></select></label>
      <label className="field"><span>وحدة القياس</span><select value={form.unitOfMeasure} onChange={e=>change('unitOfMeasure',e.target.value)}>{Object.entries(units).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
      <Field label="الحد الأدنى" type="number" step="0.001" value={form.minimumRequestQuantity} onChange={v=>change('minimumRequestQuantity',Number(v))}/><Field label="الحد الأعلى" type="number" step="0.001" value={form.maximumRequestQuantity} onChange={v=>change('maximumRequestQuantity',v)}/><Field label="خطوة الكمية" type="number" step="0.001" value={form.quantityStep} onChange={v=>change('quantityStep',Number(v))}/>
      <Field label="الترتيب" type="number" value={form.sortOrder} onChange={v=>change('sortOrder',Number(v))}/><label className="field check"><input type="checkbox" checked={form.quoteEnabled} onChange={e=>change('quoteEnabled',e.target.checked)}/> متاح لطلب عرض</label><label className="field check"><input type="checkbox" checked={form.isFeatured} onChange={e=>change('isFeatured',e.target.checked)}/> منتج مميز</label>
    </div></section>
    <section className="editor-section"><h3>الوصف</h3><div className="form-grid"><label className="field full"><span>الوصف المختصر بالعربية</span><textarea rows={2} value={form.shortDescriptionAr} onChange={e=>change('shortDescriptionAr',e.target.value)}/></label><label className="field full"><span>الوصف المختصر بالإنجليزية</span><textarea dir="ltr" rows={2} value={form.shortDescriptionEn} onChange={e=>change('shortDescriptionEn',e.target.value)}/></label><label className="field full"><span>الوصف التفصيلي بالعربية</span><textarea rows={4} value={form.detailedDescriptionAr} onChange={e=>change('detailedDescriptionAr',e.target.value)}/></label><label className="field full"><span>الوصف التفصيلي بالإنجليزية</span><textarea dir="ltr" rows={4} value={form.detailedDescriptionEn} onChange={e=>change('detailedDescriptionEn',e.target.value)}/></label></div></section>
    <section className="editor-section"><div className="section-head"><h3>المواصفات</h3><button type="button" className="button secondary small" onClick={()=>setSpecs(current=>[...current,{key:'',value:''}])}>إضافة مواصفة</button></div>{specs.length===0?<p className="muted">لم تضف مواصفات بعد.</p>:specs.map((item,index)=><div className="row-editor" key={index}><input placeholder="المواصفة" value={item.key} onChange={e=>setSpecs(current=>current.map((s,i)=>i===index?{...s,key:e.target.value}:s))}/><input placeholder="القيمة" value={item.value} onChange={e=>setSpecs(current=>current.map((s,i)=>i===index?{...s,value:e.target.value}:s))}/><button type="button" className="icon-danger" onClick={()=>setSpecs(current=>current.filter((_,i)=>i!==index))}>حذف</button></div>)}</section>
    <section className="editor-section"><div className="section-head"><h3>الصور</h3><button type="button" className="button secondary small" onClick={()=>setMediaOpen(true)}>اختيار من مكتبة الوسائط</button></div><div className="image-manager">{images.map((image,index)=><div className={'image-editor '+(image.isPrimary?'primary':'')} key={image.mediaAssetId??image.imageUrl} draggable onDragStart={()=>setDragIndex(index)} onDragOver={e=>e.preventDefault()} onDrop={e=>drop(e,index)}><img src={image.imageUrl} alt={image.altTextAr}/><div><input value={image.altTextAr} placeholder="النص البديل بالعربية" onChange={e=>updateImage(index,{altTextAr:e.target.value})}/><input dir="ltr" value={image.altTextEn} placeholder="Alt text English" onChange={e=>updateImage(index,{altTextEn:e.target.value})}/><div className="mini-actions"><button type="button" onClick={()=>setPrimary(index)}>{image.isPrimary?'الصورة الرئيسية':'تعيين كرئيسية'}</button><button type="button" onClick={()=>reorder(index,index-1)}>→</button><button type="button" onClick={()=>reorder(index,index+1)}>←</button><button type="button" className="danger-text" onClick={()=>setImages(current=>current.filter((_,i)=>i!==index))}>حذف</button></div></div></div>)}</div></section>
    <section className="editor-section"><div className="section-head"><h3>المتغيرات والخصائص</h3><button type="button" className="button secondary small" onClick={()=>setVariants(current=>[...current,emptyVariant()])}>إضافة متغير</button></div>{variants.map((variant,index)=><div className="variant-editor" key={variant.id??index}><div className="form-grid"><Field label="الاسم بالعربية" value={variant.titleAr} onChange={v=>updateVariant(index,{titleAr:v})} required/><Field label="الاسم بالإنجليزية" value={variant.titleEn} onChange={v=>updateVariant(index,{titleEn:v})}/><Field label="SKU" value={variant.sku} onChange={v=>updateVariant(index,{sku:v})}/><Field label="Barcode" value={variant.barcode} onChange={v=>updateVariant(index,{barcode:v})}/>{availableAttributes.filter(a=>a.input_type==='select').map(attribute=><label className="field" key={attribute.id}><span>{attribute.name_ar}</span><select value={(attribute.values??[]).find((v:Row)=>variant.attributeValueIds.includes(v.id))?.id??''} onChange={e=>selectAttribute(index,attribute,e.target.value)}><option value="">غير محدد</option>{(attribute.values??[]).map((value:Row)=><option key={value.id} value={value.id}>{value.value_ar}</option>)}</select></label>)}</div><div className="mini-actions"><label><input type="checkbox" checked={variant.isActive} onChange={e=>updateVariant(index,{isActive:e.target.checked})}/> فعّال</label><label><input type="radio" name="default-variant" checked={variant.isDefault} onChange={()=>setDefaultVariant(index)}/> افتراضي</label><button type="button" className="danger-text" onClick={()=>setVariants(current=>current.filter((_,i)=>i!==index))}>حذف المتغير</button></div></div>)}</section>
    <section className="editor-section"><h3>الربط والفلاتر</h3><div className="selection-grid"><CheckList label="التصنيفات الإضافية" items={lookups.categories.filter(c=>c.id!==form.categoryId)} selected={form.extraCategoryIds} onChange={ids=>change('extraCategoryIds',ids)}/><CheckList label="المنتجات المرتبطة" items={lookups.products} selected={form.relatedProductIds} onChange={ids=>change('relatedProductIds',ids)}/><fieldset className="choice-list"><legend>قيم الفلاتر</legend>{filterValues.map(value=><label key={value.id}><input type="checkbox" checked={form.filterValueIds.includes(value.id)} onChange={e=>change('filterValueIds',e.target.checked?[...form.filterValueIds,value.id]:form.filterValueIds.filter((id:string)=>id!==value.id))}/>{value.group}: {value.value_ar}</label>)}</fieldset></div>{rangeFilters.length>0&&<div className="form-grid range-fields">{rangeFilters.map(filter=><Field key={filter.id} label={filter.name_ar} type="number" step="0.001" value={form.filterRanges.find((r:Row)=>r.filterId===filter.id)?.value??''} onChange={value=>change('filterRanges',[...form.filterRanges.filter((r:Row)=>r.filterId!==filter.id),{filterId:filter.id,value}])}/>)}</div>}</section>
    <section className="editor-section"><h3>SEO</h3><div className="form-grid"><Field label="عنوان SEO بالعربية" value={form.seoTitleAr} onChange={v=>change('seoTitleAr',v)}/><Field label="SEO title English" value={form.seoTitleEn} onChange={v=>change('seoTitleEn',v)}/><label className="field"><span>وصف SEO بالعربية</span><textarea rows={3} value={form.seoDescriptionAr} onChange={e=>change('seoDescriptionAr',e.target.value)}/></label><label className="field"><span>SEO description English</span><textarea dir="ltr" rows={3} value={form.seoDescriptionEn} onChange={e=>change('seoDescriptionEn',e.target.value)}/></label></div></section>
    <div className="dialog-actions"><button className="button" disabled={saving}>{saving?'جارٍ الحفظ…':'حفظ المنتج'}</button><button type="button" className="button secondary" onClick={close}>إلغاء</button></div>
    {mediaOpen&&<div className="nested-dialog"><div className="media-picker"><div className="dialog-head"><h3>مكتبة الوسائط</h3><button type="button" className="close" onClick={()=>setMediaOpen(false)}>×</button></div><div className="media-picker-grid">{lookups.media.filter(item=>item.mime_type?.startsWith('image/')).map(asset=><button type="button" className={images.some(image=>image.mediaAssetId===asset.id)?'selected':''} key={asset.id} onClick={()=>addMedia(asset)}><img src={asset.public_url} alt={asset.alt_text_ar??''}/><span>{images.some(image=>image.mediaAssetId===asset.id)?'تم الاختيار':'اختيار'}</span></button>)}</div><div className="dialog-actions"><button type="button" className="button" onClick={()=>setMediaOpen(false)}>تم</button></div></div></div>}
  </form></div>;
}

export function ImportProducts({close,done}:{close:()=>void;done:()=>Promise<void>}){
  const[result,setResult]=useState<Row|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setLoading(true);setError('');try{const form=new FormData(event.currentTarget);
    const response=await api<Row>('/admin/products/import',{method:'POST',body:form});setResult(response);if(response.imported)await done();}catch(value){setError((value as Error).message);}finally{setLoading(false);}};
  return <div className="dialog-backdrop"><form className="dialog import-dialog" onSubmit={submit}><div className="dialog-head"><h2>استيراد المنتجات من Excel</h2><button type="button" className="close" onClick={close}>×</button></div><p className="muted">استخدم أسماء أعمدة ملف التصدير. يتم التحقق من كل الصفوف أولًا، ولن يُحفظ أي صف إذا احتوى الملف على أخطاء.</p>{error&&<div className="error">{error}</div>}<label className="upload-drop"><input name="file" type="file" accept=".xlsx" required/><span>اختر ملف Excel بصيغة .xlsx</span></label>{result&&<div className={result.errors?.length?'error':'success'}>{result.errors?.length?<><strong>لم يتم الاستيراد. الأخطاء:</strong><ul>{result.errors.map((item:Row,index:number)=><li key={index}>{item.row?`الصف ${item.row}: `:''}{item.message}</li>)}</ul></>:`تم استيراد ${result.imported} منتج بنجاح.`}</div>}<div className="dialog-actions"><button className="button" disabled={loading}>{loading?'جارٍ التحقق…':'بدء الاستيراد'}</button><button type="button" className="button secondary" onClick={close}>إغلاق</button></div></form></div>;
}
