import { useEffect, useMemo, useState } from 'react';
import { api, type Row } from '../api';
import { ProductCard } from '../components/ProductCard';
import type { Page } from '../navigation';
import { useSeo } from '../seo';
export function CatalogPage({lang,page,navigate}:{lang:'ar'|'en';page:Extract<Page,{name:'catalog'}>;navigate:(page:Page)=>void}){const[products,setProducts]=useState<Row[]>([]),[definitions,setDefinitions]=useState<Row[]>([]),[search,setSearch]=useState(''),[selected,setSelected]=useState<Record<string,Row>>({}),[loading,setLoading]=useState(true),[error,setError]=useState('');useSeo({title:lang==='ar'?'الكتالوج':'Catalog',canonicalPath:page.scope==='category'&&page.key?`/categories/${page.key}`:'/products',noIndex:Boolean(search||Object.keys(selected).length)});
  useEffect(()=>{api<Row[]>('/catalog/filters'+(page.scope==='category'&&page.key?'?category='+encodeURIComponent(page.key):'')).then(setDefinitions).catch(()=>setDefinitions([]));},[page.key,page.scope]);
  const filters=useMemo(()=>Object.entries(selected).map(([slug,value])=>({slug,...value})).filter(item=>Object.keys(item).length>1),[selected]);
  useEffect(()=>{const query=new URLSearchParams({pageSize:'48'});if(search)query.set('search',search);if(page.scope&&page.key)query.set(page.scope,page.key);if(filters.length)query.set('filters',JSON.stringify(filters));setLoading(true);setError('');api<{items:Row[]}>(`/catalog/products?${query}`).then(result=>setProducts(result.items)).catch(value=>setError((value as Error).message)).finally(()=>setLoading(false));},[search,page.scope,page.key,JSON.stringify(filters)]);
  const setFilter=(slug:string,value:Row)=>setSelected(current=>{const next={...current};if(Object.values(value).every(item=>item===''||item===undefined))delete next[slug];else next[slug]=value;return next;});
  return <main className="container section"><div className="section-head"><div><span className="eyebrow dark">{lang==='ar'?'كتالوج المعدات':'Equipment catalog'}</span><h1>{lang==='ar'?'المنتجات والموديلات':'Products and models'}</h1></div></div><div className="catalog-layout"><aside className="catalog-sidebar"><label className="field"><span>{lang==='ar'?'بحث بالمنتج أو كود الموديل':'Search product or model code'}</span><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="GT-QSJT"/></label>{definitions.map(definition=><div className="filter-block" key={definition.id}><strong>{lang==='ar'?definition.name_ar:definition.name_en??definition.name_ar}</strong>{definition.value_type==='option'?<select value={selected[definition.slug]?.optionKey??''} onChange={event=>setFilter(definition.slug,{optionKey:event.target.value})}><option value="">{lang==='ar'?'الكل':'All'}</option>{(definition.options??[]).map((option:Row)=><option key={option.id} value={option.value_key}>{lang==='ar'?option.label_ar:option.label_en??option.label_ar}</option>)}</select>:definition.value_type==='number'||definition.value_type==='range'?<div className="range-inputs"><input type="number" placeholder={lang==='ar'?'من':'Min'} value={selected[definition.slug]?.min??''} onChange={event=>setFilter(definition.slug,{...selected[definition.slug],min:event.target.value===''?undefined:Number(event.target.value)})}/><input type="number" placeholder={lang==='ar'?'إلى':'Max'} value={selected[definition.slug]?.max??''} onChange={event=>setFilter(definition.slug,{...selected[definition.slug],max:event.target.value===''?undefined:Number(event.target.value)})}/></div>:definition.value_type==='boolean'?<select value={String(selected[definition.slug]?.boolean??'')} onChange={event=>setFilter(definition.slug,{boolean:event.target.value===''?undefined:event.target.value==='true'})}><option value="">{lang==='ar'?'الكل':'All'}</option><option value="true">{lang==='ar'?'نعم':'Yes'}</option><option value="false">{lang==='ar'?'لا':'No'}</option></select>:<input value={selected[definition.slug]?.text??''} onChange={event=>setFilter(definition.slug,{text:event.target.value})}/>}</div>)}</aside><section>{error&&<div className="error">{error}</div>}{loading?<div className="empty">{lang==='ar'?'جارٍ التحميل…':'Loading…'}</div>:products.length?<div className="product-grid catalog-products">{products.map(product=><ProductCard key={product.id} product={product} lang={lang} navigate={navigate}/>)}</div>:<div className="empty">{lang==='ar'?'لا توجد موديلات مطابقة.':'No matching models.'}</div>}</section></div></main>;
}
