import { useEffect, useState } from 'react';
import { api, type Row } from '../api';
import { ProductCard } from '../components/ProductCard';
import type { Page } from '../navigation';
import { useSeo } from '../seo';
export function HomePage({lang,navigate}:{lang:'ar'|'en';navigate:(page:Page)=>void}){const[categories,setCategories]=useState<Row[]>([]),[products,setProducts]=useState<Row[]>([]);useSeo({title:lang==='ar'?'كتالوج المعدات الصناعية':'Industrial equipment catalog',canonicalPath:'/'});useEffect(()=>{Promise.all([api<Row[]>('/catalog/categories'),api<{items:Row[]}>('/catalog/products?featured=true&pageSize=6')]).then(([c,p])=>{setCategories(c);setProducts(p.items);});},[]);
  return <><section className="hero"><div className="container hero-grid"><div><span className="eyebrow">{lang==='ar'?'حلول تجهيز احترافية':'Professional equipment solutions'}</span><h1>{lang==='ar'?'اختر الجهاز بالموديل والمواصفات الدقيقة':'Choose by exact model and specifications'}</h1><p>{lang==='ar'?'قارن الموديلات، راجع صورها ومواصفاتها، ثم أرسل طلب عرض واحد.':'Compare models, review their galleries and specifications, then submit one quote request.'}</p><div className="actions"><button className="button" onClick={()=>navigate({name:'catalog'})}>{lang==='ar'?'استعرض الكتالوج':'Browse catalog'}</button></div></div><div className="hero-card"><h2>{lang==='ar'?'كيف تعمل؟':'How it works'}</h2><ul><li>1. {lang==='ar'?'اختر القسم والمنتج':'Choose a category and product'}</li><li>2. {lang==='ar'?'حدد موديل الجهاز':'Select the equipment model'}</li><li>3. {lang==='ar'?'أرسل الكمية المطلوبة':'Send the required quantity'}</li></ul></div></div></section>
    <section className="container section"><div className="section-head"><div><span className="eyebrow dark">{lang==='ar'?'الأقسام':'Categories'}</span><h2>{lang==='ar'?'تصفح حسب القسم':'Browse by category'}</h2></div></div><div className="category-grid">{categories.map(category=><button className="category-card" key={category.id} onClick={()=>navigate({name:'catalog',scope:'category',key:category.slug})}>{category.image_url&&<img src={category.image_url} alt=""/>}<strong>{lang==='ar'?category.title_ar:category.title_en??category.title_ar}</strong><span>{(category.children??[]).length} {lang==='ar'?'أقسام فرعية':'subcategories'}</span></button>)}</div></section>
    <section className="section alt"><div className="container"><div className="section-head"><h2>{lang==='ar'?'منتجات مختارة':'Featured products'}</h2><button className="button secondary" onClick={()=>navigate({name:'catalog'})}>{lang==='ar'?'عرض الكل':'View all'}</button></div><div className="product-grid">{products.map(product=><ProductCard key={product.id} product={product} lang={lang} navigate={navigate}/>)}</div></div></section></>;
}
