import { useEffect, useMemo, useState } from 'react';
import { api, track, type Row } from '../api';
import { addModel } from '../cart';
import { ModelGallery } from '../components/product/ModelGallery';
import { ModelsComparison } from '../components/product/ModelsComparison';
import { ModelSelector } from '../components/product/ModelSelector';
import { ModelSpecifications } from '../components/product/ModelSpecifications';
import type { Page } from '../navigation';
import { useSeo } from '../seo';
export function ProductPage({lang,page,navigate}:{lang:'ar'|'en';page:Extract<Page,{name:'product'}>;navigate:(page:Page,replace?:boolean)=>void}){const[product,setProduct]=useState<Row|null>(null),[selectedId,setSelectedId]=useState(''),[quantity,setQuantity]=useState(1),[note,setNote]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState('');
  const schemaModelRelation='has'+String.fromCharCode(86)+'ariant';
  useEffect(()=>{setError('');api<Row>(`/catalog/products/${encodeURIComponent(page.slug)}${page.modelCode?'/models/'+encodeURIComponent(page.modelCode):''}`).then(data=>{setProduct(data);const id=data.selectedModelId??data.defaultModelId??data.models?.[0]?.id;setSelectedId(id);const model=data.models?.find((item:Row)=>item.id===id);setQuantity(Number(model?.minimum_request_quantity??1));void track('product_viewed',{productId:data.id,modelId:id});}).catch(value=>setError((value as Error).message));},[page.slug,page.modelCode]);
  const model=useMemo(()=>product?.models?.find((item:Row)=>item.id===selectedId)??product?.models?.[0],[product,selectedId]);const title=product?(lang==='ar'?product.title_ar:product.title_en??product.title_ar):'';const modelTitle=model?`${title} ${model.model_code}`:title;
  useSeo({title:modelTitle,description:lang==='ar'?product?.short_description_ar:product?.short_description_en,image:model?.images?.[0]?.image_url,canonicalPath:model?`/products/${page.slug}/models/${encodeURIComponent(model.model_code)}`:`/products/${page.slug}`,structuredData:product&&model?{'@context':'https://schema.org','@type':'ProductGroup',name:title,productGroupID:product.id,brand:product.brand_title_ar?{'@type':'Brand',name:lang==='ar'?product.brand_title_ar:product.brand_title_en}:undefined,[schemaModelRelation]:product.models.map((item:Row)=>({'@type':'Product',name:`${title} ${item.model_code}`,sku:item.sku??item.model_code,url:`${location.origin}/products/${page.slug}/models/${encodeURIComponent(item.model_code)}`}))}:null});
  if(error)return <main className="container section"><div className="error">{error}</div></main>;if(!product||!model)return <main className="container section"><div className="empty">{lang==='ar'?'جارٍ التحميل…':'Loading…'}</div></main>;
  const select=(next:Row)=>{setSelectedId(next.id);setQuantity(Number(next.minimum_request_quantity));setMessage('');navigate({name:'product',slug:page.slug,modelCode:next.model_code},true);void track('model_selected',{productId:product.id,modelId:next.id,metadata:{modelCode:next.model_code}});};
  const add=async(target=model)=>{try{await addModel(product.id,target.id,target.id===model.id?quantity:Number(target.minimum_request_quantity));setMessage(lang==='ar'?'تمت إضافة الموديل إلى طلب العرض.':'Model added to quote cart.');void track('model_added_to_quote',{productId:product.id,modelId:target.id});}catch(value){setMessage((value as Error).message);}};
  const available=model.is_active&&model.quote_enabled&&!['hidden','discontinued'].includes(model.availability_status);return <main><div className="container"><nav className="breadcrumbs">{(product.breadcrumbs??[]).map((crumb:Row)=><button key={crumb.id} onClick={()=>navigate({name:'catalog',scope:'category',key:crumb.slug})}>{lang==='ar'?crumb.title_ar:crumb.title_en??crumb.title_ar}</button>)}<span>{title}</span></nav><section className="detail"><ModelGallery images={model.images??[]} title={modelTitle}/><div><span className="eyebrow dark">{lang==='ar'?product.brand_title_ar:product.brand_title_en}</span><h1>{title}</h1><div className="selected-model-code">{model.model_code}</div><p className="muted detail-description">{lang==='ar'?model.description_ar??product.description_ar:model.description_en??product.description_en}</p><ModelSelector models={product.models} selectedId={model.id} onSelect={select} lang={lang}/><div className={'availability '+model.availability_status}>{model.availability_status}</div>
      {(model.datasheet_url||model.manual_url)&&<div className="document-links">{model.datasheet_url&&<a href={model.datasheet_url} target="_blank" rel="noreferrer">Datasheet PDF</a>}{model.manual_url&&<a href={model.manual_url} target="_blank" rel="noreferrer">Manual PDF</a>}</div>}
      <div className="quote-box"><h3>{lang==='ar'?'أضف الموديل لطلب العرض':'Add model to quote'}</h3><label className="field"><span>{lang==='ar'?'الكمية':'Quantity'} ({model.unit_of_measure})</span><input type="number" min={model.minimum_request_quantity} max={model.maximum_request_quantity??undefined} step={model.quantity_step} value={quantity} onChange={event=>setQuantity(Number(event.target.value))}/></label><label className="field"><span>{lang==='ar'?'ملاحظة':'Note'}</span><textarea rows={2} value={note} onChange={event=>setNote(event.target.value)}/></label><button className="button" disabled={!available} onClick={()=>void add()}>{lang==='ar'?'إضافة إلى طلب العرض':'Add to quote'}</button>{message&&<div className={message.startsWith('تم')||message.startsWith('Model')?'notice':'error'}>{message}</div>}</div></div></section>
    <section className="section product-spec-section"><div className="section-head"><h2>{lang==='ar'?'مواصفات الموديل':'Model specifications'}</h2></div><ModelSpecifications specifications={model.specifications??[]} lang={lang}/></section><ModelsComparison models={product.models} lang={lang} onAdd={target=>void add(target)}/></div></main>;
}
