import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react';
import { api, type Row } from '../api';
import { cartToken, clearCartToken, getCart, removeCartItem, updateCartItem } from '../cart';
import type { Page } from '../navigation';
import { useSeo } from '../seo';
export function QuoteCartPage({lang,navigate}:{lang:'ar'|'en';navigate:(page:Page)=>void}){const[data,setData]=useState<Row|null>(null),[error,setError]=useState(''),[sending,setSending]=useState(false);const started=useRef(new Date().toISOString());useSeo({title:lang==='ar'?'طلب عرض السعر':'Quote request',canonicalPath:'/cart',noIndex:true});
  const load=useCallback(()=>getCart().then(setData),[]);useEffect(()=>{void load();},[load]);const items=data?.items??[];
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setSending(true);setError('');try{const fields=new FormData(event.currentTarget);const body={cartToken:cartToken(),fullName:fields.get('fullName'),phone:fields.get('phone'),email:fields.get('email')||undefined,companyName:fields.get('companyName')||undefined,city:fields.get('city')||undefined,customerNote:fields.get('customerNote')||undefined,preferredContactMethod:'phone',source:'web',formStartedAt:started.current,website:fields.get('website')||undefined};const result=await api<Row>('/quote-requests',{method:'POST',headers:{'idempotency-key':crypto.randomUUID()},body:JSON.stringify(body)});clearCartToken();navigate({name:'success',data:result});}catch(value){setError((value as Error).message);}finally{setSending(false);}};
  return <main className="container section"><div className="section-head"><h1>{lang==='ar'?'طلب عرض السعر':'Quote request'}</h1></div>{error&&<div className="error">{error}</div>}{!items.length?<div className="empty"><p>{lang==='ar'?'السلة فارغة. اختر موديلًا محددًا من الكتالوج.':'The cart is empty. Choose a specific model from the catalog.'}</p><button className="button" onClick={()=>navigate({name:'catalog'})}>{lang==='ar'?'فتح الكتالوج':'Open catalog'}</button></div>:<div className="cart-layout"><section className="panel"><h2>{lang==='ar'?'الموديلات المطلوبة':'Requested models'}</h2>{items.map((item:Row)=><article className="cart-item" key={item.id}>{item.image_url&&<img src={item.image_url} alt=""/>}<div><strong>{lang==='ar'?item.title_ar:item.title_en??item.title_ar}</strong><div className="selected-model-code">{item.model_code}</div><button className="link-button" onClick={()=>navigate({name:'product',slug:item.slug,modelCode:item.model_code})}>{lang==='ar'?'العودة إلى الموديل':'Back to model'}</button></div><div><input aria-label={lang==='ar'?'الكمية':'Quantity'} className="quantity" type="number" min="0.001" step="0.001" defaultValue={item.quantity} onBlur={async event=>{try{await updateCartItem(item.id,Number(event.target.value));await load();}catch(value){setError((value as Error).message);}}}/><button className="danger-link" onClick={async()=>{await removeCartItem(item.id);await load();}}>{lang==='ar'?'حذف':'Remove'}</button></div></article>)}</section><form className="panel quote-contact" onSubmit={submit}><h2>{lang==='ar'?'بيانات التواصل':'Contact details'}</h2><div className="form-grid"><label className="field full"><span>{lang==='ar'?'الاسم':'Name'}</span><input name="fullName" required maxLength={200}/></label><label className="field"><span>{lang==='ar'?'الهاتف':'Phone'}</span><input name="phone" required inputMode="tel"/></label><label className="field"><span>{lang==='ar'?'البريد':'Email'}</span><input name="email" type="email"/></label><label className="field"><span>{lang==='ar'?'الشركة':'Company'}</span><input name="companyName"/></label><label className="field"><span>{lang==='ar'?'المدينة':'City'}</span><input name="city"/></label><label className="field full"><span>{lang==='ar'?'ملاحظة عامة':'General note'}</span><textarea name="customerNote" rows={4}/></label><input className="honeypot" name="website" tabIndex={-1} autoComplete="off"/></div><button className="button" disabled={sending}>{sending?(lang==='ar'?'جارٍ الإرسال…':'Sending…'):(lang==='ar'?'إرسال طلب العرض':'Submit quote request')}</button></form></div>}</main>;
}
