CREATE INDEX admin_sessions_user_idx ON admin_sessions(admin_user_id, revoked_at);
CREATE INDEX audit_logs_created_idx ON audit_logs(created_at DESC);
CREATE INDEX products_public_idx ON products(status, quote_enabled, sort_order, created_at DESC);
CREATE INDEX products_category_idx ON products(category_id);
CREATE INDEX products_brand_idx ON products(brand_id);
CREATE INDEX products_tags_gin_idx ON products USING GIN(tags);
CREATE INDEX products_specifications_gin_idx ON products USING GIN(specifications);
CREATE UNIQUE INDEX product_primary_image_unique ON product_images(product_id) WHERE is_primary;
CREATE UNIQUE INDEX product_default_variant_unique ON product_variants(product_id) WHERE is_default = TRUE AND is_active = TRUE;
CREATE INDEX quote_carts_expiry_idx ON quote_carts(status, expires_at);
CREATE INDEX quote_requests_status_created_idx ON quote_requests(status, created_at DESC);
CREATE INDEX quote_requests_contact_idx ON quote_requests(contact_id, created_at DESC);
CREATE INDEX quote_requests_assignee_idx ON quote_requests(assigned_to_admin_user_id, status);
CREATE INDEX quote_requests_search_idx ON quote_requests(request_number, phone);
CREATE INDEX quote_request_items_product_idx ON quote_request_items(product_id);
CREATE INDEX notification_recipients_user_unread_idx ON notification_recipients(admin_user_id, read_at, notification_id);
CREATE INDEX notifications_created_at_idx ON notifications(created_at DESC);
CREATE INDEX outbox_pending_idx ON outbox_events(status, available_at) WHERE status IN ('pending','failed');
CREATE INDEX catalog_events_name_created_idx ON catalog_events(event_name, created_at DESC);
CREATE INDEX catalog_events_product_idx ON catalog_events(product_id, created_at DESC);
