WITH professional_templates (
  template_key,
  name,
  description,
  category,
  component_key,
  thumbnail_url,
  preview_image_url,
  preview_images,
  tags,
  suitable_for,
  settings_schema,
  settings,
  capabilities
) AS (
  VALUES
    (
      'general-starter',
      'General Starter',
      'قالب متجر عربي حديث يناسب أغلب المتاجر، مع واجهة بيع واضحة وتصنيفات ومنتجات وثقة شرائية.',
      'general',
      'general-starter',
      'https://cdn.your-domain.com/templates/general-starter/thumb.webp',
      'https://cdn.your-domain.com/templates/general-starter/home.webp',
      '["https://cdn.your-domain.com/templates/general-starter/home.webp","https://cdn.your-domain.com/templates/general-starter/products.webp","https://cdn.your-domain.com/templates/general-starter/mobile.webp"]'::jsonb,
      ARRAY['rtl','modern','general']::text[],
      'المتاجر العامة، الهدايا، المنتجات المنزلية، والمتاجر التي تحتاج بداية احترافية سريعة.',
      '{"hero.eyebrow":{"type":"text","label":"عبارة أعلى الواجهة","maxLength":60},"hero.headline":{"type":"text","label":"عنوان الواجهة","maxLength":90},"hero.subheadline":{"type":"textarea","label":"وصف الواجهة","maxLength":220},"hero.imageUrl":{"type":"image","label":"صورة الواجهة"},"hero.primaryCtaLabel":{"type":"text","label":"نص زر الواجهة","maxLength":40},"hero.primaryCtaHref":{"type":"url","label":"رابط زر الواجهة"},"offer.label":{"type":"text","label":"تسمية العرض","maxLength":50},"offer.title":{"type":"text","label":"عنوان العرض","maxLength":100},"products.limit":{"type":"number","label":"عدد المنتجات","min":4,"max":16}}'::jsonb,
      '{"hero":{"eyebrow":"متجر جاهز للبيع بثقة","headline":"اكتشف أفضل اختيارات متجرنا","subheadline":"واجهة متجر حديثة تضع المنتجات المهمة، التصنيفات، والثقة الشرائية أمام العميل من أول زيارة.","primaryCtaLabel":"تسوق المنتجات","primaryCtaHref":"/categories","imageUrl":""},"offer":{"label":"عرض المتجر","title":"ابدأ رحلة الشراء من التصنيفات الأكثر طلباً","href":"/categories"},"badges":["دفع آمن","توصيل واضح","استبدال مرن"],"products":{"source":"featured","limit":8}}'::jsonb,
      '{"rtl":true,"responsive":true,"supportsOffers":true,"supportsImages":true}'::jsonb
    ),
    (
      'fashion-editorial',
      'Fashion Editorial',
      'قالب تحريري للموضة والعلامات البصرية، يبرز القصة والصورة والمنتجات المختارة.',
      'fashion',
      'fashion-editorial',
      'https://cdn.your-domain.com/templates/fashion-editorial/thumb.webp',
      'https://cdn.your-domain.com/templates/fashion-editorial/home.webp',
      '["https://cdn.your-domain.com/templates/fashion-editorial/home.webp","https://cdn.your-domain.com/templates/fashion-editorial/products.webp","https://cdn.your-domain.com/templates/fashion-editorial/mobile.webp"]'::jsonb,
      ARRAY['rtl','fashion','editorial']::text[],
      'الموضة، الإكسسوارات، المنتجات الموسمية، والعلامات التي تعتمد على الصورة.',
      '{"hero.eyebrow":{"type":"text","label":"عبارة تحريرية","maxLength":60},"hero.headline":{"type":"text","label":"عنوان الواجهة","maxLength":90},"hero.subheadline":{"type":"textarea","label":"وصف الواجهة","maxLength":220},"hero.imageUrl":{"type":"image","label":"صورة الواجهة"},"story.title":{"type":"text","label":"عنوان قصة العلامة","maxLength":90},"story.body":{"type":"textarea","label":"نص قصة العلامة","maxLength":420},"products.limit":{"type":"number","label":"عدد المنتجات","min":4,"max":12}}'::jsonb,
      '{"hero":{"eyebrow":"تحرير موسمي","headline":"إطلالة موسمية بتفاصيل لا تنسى","subheadline":"اعرض منتجاتك بأسلوب تحريري فاخر يجعل الزائر يرى القيمة من أول لحظة.","primaryCtaLabel":"تسوق المجموعة","primaryCtaHref":"/categories","imageUrl":""},"story":{"title":"اختيارات منتقاة بعناية","body":"واجهة تضع القصة البصرية والمنتج في مركز التجربة مع رحلة تسوق واضحة وسريعة."},"badges":["تصميم مختار","جودة موثوقة","تغليف أنيق"],"products":{"source":"featured","limit":8}}'::jsonb,
      '{"rtl":true,"responsive":true,"supportsStory":true,"supportsLookbook":true}'::jsonb
    ),
    (
      'electronics-pro',
      'Electronics Pro',
      'قالب عملي لمتاجر الإلكترونيات والأجهزة، يركز على المقارنة والعروض والأقسام السريعة.',
      'electronics',
      'electronics-pro',
      'https://cdn.your-domain.com/templates/electronics-pro/thumb.webp',
      'https://cdn.your-domain.com/templates/electronics-pro/home.webp',
      '["https://cdn.your-domain.com/templates/electronics-pro/home.webp","https://cdn.your-domain.com/templates/electronics-pro/products.webp","https://cdn.your-domain.com/templates/electronics-pro/mobile.webp"]'::jsonb,
      ARRAY['rtl','electronics','dense']::text[],
      'الإلكترونيات، الجوالات، الأجهزة، وملحقات التقنية.',
      '{"groups":[{"key":"appearance","label":"المظهر","fields":[{"key":"globals.color.primary","type":"color","label":"اللون الرئيسي","default":"#0f766e"},{"key":"globals.color.primaryStrong","type":"color","label":"اللون الرئيسي الداكن","default":"#115e59"},{"key":"globals.color.accent","type":"color","label":"لون التمييز","default":"#f97316"},{"key":"settings.appearance.headerStyle","type":"select","label":"شكل الهيدر","default":"marketplace","options":[{"label":"سوق إلكتروني","value":"marketplace"},{"label":"بسيط","value":"compact"}]},{"key":"settings.appearance.cardRadius","type":"select","label":"استدارة البطاقات","default":"soft","options":[{"label":"خفيفة","value":"soft"},{"label":"متوسطة","value":"medium"},{"label":"دائرية","value":"rounded"}]}]},{"key":"hero","label":"قسم الواجهة الرئيسية","fields":[{"key":"settings.hero.eyebrow","type":"text","label":"النص العلوي","default":"Electronics Pro","maxLength":60},{"key":"settings.hero.headline","type":"text","label":"عنوان الهيرو","default":"كل أجهزتك الذكية في متجر واحد","maxLength":90},{"key":"settings.hero.subheadline","type":"textarea","label":"وصف الهيرو","default":"تجربة تسوق إلكترونيات احترافية، سريعة، وواضحة لعملائك.","maxLength":220},{"key":"settings.hero.imageUrl","type":"image","label":"صورة الهيرو"},{"key":"settings.hero.variant","type":"select","label":"شكل الهيرو","default":"split","options":[{"label":"تقسيم مع صورة","value":"split"},{"label":"بانر كامل","value":"banner"}]},{"key":"settings.hero.showStats","type":"boolean","label":"إظهار الإحصائيات","default":true}]},{"key":"sections","label":"أقسام الصفحة الرئيسية","fields":[{"key":"settings.sections.showCategories","type":"boolean","label":"إظهار التصنيفات","default":true},{"key":"settings.sections.showFeaturedProducts","type":"boolean","label":"إظهار المنتجات المميزة","default":true},{"key":"settings.sections.showPromoBanners","type":"boolean","label":"إظهار بانرات العروض","default":true},{"key":"settings.sections.showBrands","type":"boolean","label":"إظهار البراندات","default":true},{"key":"settings.products.limit","type":"number","label":"عدد المنتجات المعروضة","default":12,"min":4,"max":24}]}]}'::jsonb,
      '{"appearance":{"headerStyle":"marketplace","cardRadius":"soft"},"hero":{"eyebrow":"Electronics Pro","headline":"كل أجهزتك الذكية في متجر واحد","subheadline":"تجربة تسوق إلكترونيات احترافية، سريعة، وواضحة لعملائك.","primaryCtaLabel":"تسوق الأجهزة","primaryCtaHref":"/categories","imageUrl":"","variant":"split","showStats":true},"sections":{"showCategories":true,"showFeaturedProducts":true,"showPromoBanners":true,"showBrands":true},"offer":{"label":"عرض الأسبوع","title":"خصومات على المنتجات المختارة","href":"/categories"},"badges":["ضمان موثق","دفع آمن","شحن سريع","دعم فني"],"products":{"source":"featured","limit":12}}'::jsonb,
      '{"rtl":true,"responsive":true,"supportsOffers":true,"supportsDenseCatalog":true}'::jsonb
    ),
    (
      'beauty-luxe',
      'Beauty Luxe',
      'قالب فاخر للجمال والعطور والهدايا، يبرز الصورة والقصة والتغليف.',
      'beauty',
      'beauty-luxe',
      'https://cdn.your-domain.com/templates/beauty-luxe/thumb.webp',
      'https://cdn.your-domain.com/templates/beauty-luxe/home.webp',
      '["https://cdn.your-domain.com/templates/beauty-luxe/home.webp","https://cdn.your-domain.com/templates/beauty-luxe/products.webp","https://cdn.your-domain.com/templates/beauty-luxe/mobile.webp"]'::jsonb,
      ARRAY['rtl','beauty','luxury']::text[],
      'العطور، مستحضرات الجمال، الهدايا، والمنتجات الفاخرة.',
      '{"hero.eyebrow":{"type":"text","label":"عبارة أعلى الواجهة","maxLength":60},"hero.headline":{"type":"text","label":"عنوان الواجهة","maxLength":90},"hero.subheadline":{"type":"textarea","label":"وصف الواجهة","maxLength":220},"hero.imageUrl":{"type":"image","label":"صورة الواجهة"},"story.title":{"type":"text","label":"عنوان القصة","maxLength":90},"story.body":{"type":"textarea","label":"نص القصة","maxLength":420},"products.limit":{"type":"number","label":"عدد المنتجات","min":4,"max":12}}'::jsonb,
      '{"hero":{"eyebrow":"جمال وهدايا","headline":"تجربة فاخرة لمنتجات الجمال والعطور","subheadline":"قالب يبرز الملمس، التفاصيل، وقيمة الهدية مع مسار شراء واضح وهادئ.","primaryCtaLabel":"تسوق المجموعة","primaryCtaHref":"/categories","imageUrl":""},"story":{"title":"تفاصيل صغيرة تصنع انطباعاً كبيراً","body":"اعرض القصة، الرائحة، الإحساس، والتغليف بطريقة تجعل المنتج مرغوباً قبل الوصول إلى صفحة التفاصيل."},"badges":["مختار بعناية","تغليف فاخر","مناسب للهدايا"],"products":{"source":"featured","limit":8}}'::jsonb,
      '{"rtl":true,"responsive":true,"supportsStory":true,"supportsLuxuryCatalog":true}'::jsonb
    ),
    (
      'market-modern',
      'Market Modern',
      'قالب عملي للمتاجر كثيرة المنتجات، مناسب للبقالة والمتاجر اليومية والعروض السريعة.',
      'grocery',
      'market-modern',
      'https://cdn.your-domain.com/templates/market-modern/thumb.webp',
      'https://cdn.your-domain.com/templates/market-modern/home.webp',
      '["https://cdn.your-domain.com/templates/market-modern/home.webp","https://cdn.your-domain.com/templates/market-modern/products.webp","https://cdn.your-domain.com/templates/market-modern/mobile.webp"]'::jsonb,
      ARRAY['rtl','market','grocery']::text[],
      'البقالة، المنتجات اليومية، المتاجر الكبيرة، ومتاجر العروض.',
      '{"hero.eyebrow":{"type":"text","label":"عبارة أعلى الواجهة","maxLength":60},"hero.headline":{"type":"text","label":"عنوان الواجهة","maxLength":90},"hero.subheadline":{"type":"textarea","label":"وصف الواجهة","maxLength":220},"offer.label":{"type":"text","label":"تسمية العرض","maxLength":50},"offer.title":{"type":"text","label":"عنوان العرض","maxLength":100},"offer.href":{"type":"url","label":"رابط العرض"},"products.limit":{"type":"number","label":"عدد المنتجات","min":4,"max":20}}'::jsonb,
      '{"hero":{"eyebrow":"تسوق يومي سريع","headline":"منتجاتك اليومية مرتبة وجاهزة للطلب","subheadline":"قالب عملي للمتاجر كثيرة المنتجات، يبرز التصنيفات والعروض ويجعل الوصول للمنتج سريعاً.","primaryCtaLabel":"ابدأ التسوق","primaryCtaHref":"/categories","imageUrl":""},"offer":{"label":"عرض اليوم","title":"وفر أكثر عند التسوق من المنتجات المختارة","href":"/categories"},"badges":["توصيل يومي","أسعار واضحة","منتجات طازجة"],"products":{"source":"featured","limit":12}}'::jsonb,
      '{"rtl":true,"responsive":true,"supportsOffers":true,"supportsDenseCatalog":true}'::jsonb
    )
)
INSERT INTO theme_templates (
  template_key,
  name,
  description,
  category,
  renderer_type,
  component_key,
  status,
  version,
  is_premium,
  allowed_plans,
  thumbnail_url,
  preview_image_url,
  preview_images,
  tags,
  suitable_for,
  assets,
  settings_schema,
  default_config,
  draft_config,
  published_config,
  capabilities,
  published_at
)
SELECT
  template_key,
  name,
  description,
  category,
  'component',
  component_key,
  'published',
  2,
  false,
  ARRAY[]::text[],
  thumbnail_url,
  preview_image_url,
  preview_images,
  tags,
  suitable_for,
  '{}'::jsonb,
  settings_schema,
  jsonb_build_object(
    'schemaVersion', 3,
    'template', jsonb_build_object('id', template_key, 'renderer', 'component', 'componentKey', component_key, 'version', 2),
    'globals', CASE WHEN template_key = 'electronics-pro' THEN jsonb_build_object(
      'color', jsonb_build_object('primary', '#0f766e', 'primaryStrong', '#115e59', 'primaryContrast', '#ffffff', 'accent', '#f97316', 'bg', '#f6f8fb', 'surface', '#ffffff', 'text', '#0f172a', 'textMuted', '#64748b', 'line', '#e2e8f0'),
      'typography', jsonb_build_object('headingFont', 'inherit', 'bodyFont', 'inherit'),
      'radius', jsonb_build_object('card', '24px', 'button', '999px'),
      'spacing', jsonb_build_object('sectionY', '64px')
    ) ELSE '{}'::jsonb END,
    'settings', settings,
    'layout', '{}'::jsonb,
    'accessibility', CASE WHEN template_key = 'electronics-pro' THEN jsonb_build_object('reducedMotion', false) ELSE '{}'::jsonb END
  ),
  jsonb_build_object(
    'schemaVersion', 3,
    'template', jsonb_build_object('id', template_key, 'renderer', 'component', 'componentKey', component_key, 'version', 2),
    'globals', CASE WHEN template_key = 'electronics-pro' THEN jsonb_build_object(
      'color', jsonb_build_object('primary', '#0f766e', 'primaryStrong', '#115e59', 'primaryContrast', '#ffffff', 'accent', '#f97316', 'bg', '#f6f8fb', 'surface', '#ffffff', 'text', '#0f172a', 'textMuted', '#64748b', 'line', '#e2e8f0'),
      'typography', jsonb_build_object('headingFont', 'inherit', 'bodyFont', 'inherit'),
      'radius', jsonb_build_object('card', '24px', 'button', '999px'),
      'spacing', jsonb_build_object('sectionY', '64px')
    ) ELSE '{}'::jsonb END,
    'settings', settings,
    'layout', '{}'::jsonb,
    'accessibility', CASE WHEN template_key = 'electronics-pro' THEN jsonb_build_object('reducedMotion', false) ELSE '{}'::jsonb END
  ),
  jsonb_build_object(
    'schemaVersion', 3,
    'template', jsonb_build_object('id', template_key, 'renderer', 'component', 'componentKey', component_key, 'version', 2),
    'globals', CASE WHEN template_key = 'electronics-pro' THEN jsonb_build_object(
      'color', jsonb_build_object('primary', '#0f766e', 'primaryStrong', '#115e59', 'primaryContrast', '#ffffff', 'accent', '#f97316', 'bg', '#f6f8fb', 'surface', '#ffffff', 'text', '#0f172a', 'textMuted', '#64748b', 'line', '#e2e8f0'),
      'typography', jsonb_build_object('headingFont', 'inherit', 'bodyFont', 'inherit'),
      'radius', jsonb_build_object('card', '24px', 'button', '999px'),
      'spacing', jsonb_build_object('sectionY', '64px')
    ) ELSE '{}'::jsonb END,
    'settings', settings,
    'layout', '{}'::jsonb,
    'accessibility', CASE WHEN template_key = 'electronics-pro' THEN jsonb_build_object('reducedMotion', false) ELSE '{}'::jsonb END
  ),
  capabilities,
  NOW()
FROM professional_templates
ON CONFLICT (template_key) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  renderer_type = EXCLUDED.renderer_type,
  component_key = EXCLUDED.component_key,
  status = EXCLUDED.status,
  version = EXCLUDED.version,
  is_premium = EXCLUDED.is_premium,
  allowed_plans = EXCLUDED.allowed_plans,
  thumbnail_url = EXCLUDED.thumbnail_url,
  preview_image_url = EXCLUDED.preview_image_url,
  preview_images = EXCLUDED.preview_images,
  tags = EXCLUDED.tags,
  suitable_for = EXCLUDED.suitable_for,
  assets = EXCLUDED.assets,
  settings_schema = EXCLUDED.settings_schema,
  default_config = EXCLUDED.default_config,
  draft_config = EXCLUDED.draft_config,
  published_config = EXCLUDED.published_config,
  capabilities = EXCLUDED.capabilities,
  published_at = EXCLUDED.published_at,
  archived_at = NULL,
  updated_at = NOW();
