UPDATE theme_templates
SET
  settings_schema = '{"hero.eyebrow":{"type":"text","label":"عبارة أعلى الواجهة","maxLength":60},"hero.headline":{"type":"text","label":"عنوان الواجهة","maxLength":90},"hero.subheadline":{"type":"textarea","label":"وصف الواجهة","maxLength":220},"hero.imageUrl":{"type":"image","label":"صورة الواجهة"},"hero.primaryCtaLabel":{"type":"text","label":"نص زر الواجهة","maxLength":40},"hero.primaryCtaHref":{"type":"url","label":"رابط زر الواجهة"},"offer.label":{"type":"text","label":"تسمية العرض","maxLength":50},"offer.title":{"type":"text","label":"عنوان العرض","maxLength":100},"products.limit":{"type":"number","label":"عدد المنتجات","min":4,"max":16}}'::jsonb,
  default_config = '{"schemaVersion":3,"template":{"id":"general-starter","renderer":"component","componentKey":"general-starter","version":2},"globals":{},"settings":{"hero":{"eyebrow":"متجر جاهز للبيع بثقة","headline":"اكتشف أفضل اختيارات متجرنا","subheadline":"واجهة متجر حديثة تضع المنتجات المهمة، التصنيفات، والثقة الشرائية أمام العميل من أول زيارة.","primaryCtaLabel":"تسوق المنتجات","primaryCtaHref":"/categories","imageUrl":""},"offer":{"label":"عرض المتجر","title":"ابدأ رحلة الشراء من التصنيفات الأكثر طلباً","href":"/categories"},"badges":["دفع آمن","توصيل واضح","استبدال مرن"],"products":{"source":"featured","limit":8}},"layout":{},"accessibility":{}}'::jsonb,
  draft_config = '{"schemaVersion":3,"template":{"id":"general-starter","renderer":"component","componentKey":"general-starter","version":2},"globals":{},"settings":{"hero":{"eyebrow":"متجر جاهز للبيع بثقة","headline":"اكتشف أفضل اختيارات متجرنا","subheadline":"واجهة متجر حديثة تضع المنتجات المهمة، التصنيفات، والثقة الشرائية أمام العميل من أول زيارة.","primaryCtaLabel":"تسوق المنتجات","primaryCtaHref":"/categories","imageUrl":""},"offer":{"label":"عرض المتجر","title":"ابدأ رحلة الشراء من التصنيفات الأكثر طلباً","href":"/categories"},"badges":["دفع آمن","توصيل واضح","استبدال مرن"],"products":{"source":"featured","limit":8}},"layout":{},"accessibility":{}}'::jsonb,
  published_config = '{"schemaVersion":3,"template":{"id":"general-starter","renderer":"component","componentKey":"general-starter","version":2},"globals":{},"settings":{"hero":{"eyebrow":"متجر جاهز للبيع بثقة","headline":"اكتشف أفضل اختيارات متجرنا","subheadline":"واجهة متجر حديثة تضع المنتجات المهمة، التصنيفات، والثقة الشرائية أمام العميل من أول زيارة.","primaryCtaLabel":"تسوق المنتجات","primaryCtaHref":"/categories","imageUrl":""},"offer":{"label":"عرض المتجر","title":"ابدأ رحلة الشراء من التصنيفات الأكثر طلباً","href":"/categories"},"badges":["دفع آمن","توصيل واضح","استبدال مرن"],"products":{"source":"featured","limit":8}},"layout":{},"accessibility":{}}'::jsonb,
  capabilities = '{"rtl":true,"responsive":true,"supportsOffers":true,"supportsImages":true}'::jsonb,
  version = GREATEST(version - 1, 1),
  updated_at = NOW()
WHERE template_key = 'general-starter';
