export type MerchantNotificationCategory =
  | 'orders'
  | 'payments'
  | 'inventory'
  | 'cart'
  | 'checkout'
  | 'support'
  | 'domain'
  | 'analytics'
  | 'system';

export type MerchantNotificationSeverity = 'info' | 'success' | 'warning' | 'critical';
export type MerchantNotificationRecipientType = 'store' | 'store_user' | 'customer';
export type MerchantNotificationFrequency = 'instant' | 'daily_digest' | 'mute';

export interface MerchantNotificationEventDefinition {
  eventType: string;
  category: MerchantNotificationCategory;
  severity: MerchantNotificationSeverity;
  recipientType: MerchantNotificationRecipientType;
  title: string;
  body: string;
  actionUrl?: string;
  defaultFrequency: MerchantNotificationFrequency;
  isPersistent: boolean;
  dedupeKey?: string;
}

type RegistryDefinitionInput = Omit<MerchantNotificationEventDefinition, 'eventType'>;

function defineRegistry<T extends Record<string, RegistryDefinitionInput>>(
  events: T,
): { [K in keyof T]: T[K] & { eventType: K & string } } {
  return Object.fromEntries(
    Object.entries(events).map(([eventType, definition]) => [
      eventType,
      { eventType, ...definition },
    ]),
  ) as { [K in keyof T]: T[K] & { eventType: K & string } };
}

export const MERCHANT_NOTIFICATION_EVENTS = defineRegistry({
  'order.created': {
    category: 'orders',
    severity: 'info',
    recipientType: 'store',
    title: 'طلب جديد',
    body: 'وصل طلب جديد {{orderCode}} بقيمة {{total}} {{currencyCode}} من العميل {{customerName}}.',
    actionUrl: '/merchant?tab=orders&orderId={{orderId}}',
    defaultFrequency: 'instant',
    isPersistent: true,
    dedupeKey: 'order.created:{{orderId}}',
  },
  'order.updated': {
    category: 'orders',
    severity: 'info',
    recipientType: 'store',
    title: 'تم تحديث طلب',
    body: 'تم تحديث الطلب {{orderCode}}.',
    actionUrl: '/merchant?tab=orders&orderId={{orderId}}',
    defaultFrequency: 'instant',
    isPersistent: true,
    dedupeKey: 'order.updated:{{orderId}}',
  },
  'order.status.changed': {
    category: 'orders',
    severity: 'info',
    recipientType: 'store',
    title: 'تغيرت حالة الطلب',
    body: 'تغيرت حالة الطلب {{orderCode}} من {{from}} إلى {{to}}.',
    actionUrl: '/merchant?tab=orders&orderId={{orderId}}',
    defaultFrequency: 'instant',
    isPersistent: true,
    dedupeKey: 'order.status.changed:{{orderId}}:{{to}}',
  },
  'order.cancelled': {
    category: 'orders',
    severity: 'warning',
    recipientType: 'store',
    title: 'تم إلغاء طلب',
    body: 'تم إلغاء الطلب {{orderCode}}.',
    actionUrl: '/merchant?tab=orders&orderId={{orderId}}',
    defaultFrequency: 'instant',
    isPersistent: true,
    dedupeKey: 'order.cancelled:{{orderId}}',
  },
  'order.paid': {
    category: 'orders',
    severity: 'success',
    recipientType: 'store',
    title: 'تم دفع الطلب',
    body: 'تم تأكيد دفع الطلب {{orderCode}}.',
    actionUrl: '/merchant?tab=orders&orderId={{orderId}}',
    defaultFrequency: 'instant',
    isPersistent: true,
    dedupeKey: 'order.paid:{{orderId}}',
  },
  'order.ready_to_fulfill': {
    category: 'orders',
    severity: 'success',
    recipientType: 'store',
    title: 'الطلب جاهز للتجهيز',
    body: 'تم تأكيد الدفع للطلب {{orderCode}} وأصبح جاهزًا للتجهيز.',
    actionUrl: '/merchant?tab=orders&orderId={{orderId}}',
    defaultFrequency: 'instant',
    isPersistent: true,
    dedupeKey: 'order.ready_to_fulfill:{{orderId}}',
  },
  'payment.receipt_uploaded': {
    category: 'payments',
    severity: 'warning',
    recipientType: 'store',
    title: 'إيصال دفع جديد',
    body: 'تم رفع إيصال دفع للطلب {{orderCode}} ويحتاج مراجعة.',
    actionUrl: '/merchant?tab=payments&paymentId={{paymentId}}',
    defaultFrequency: 'instant',
    isPersistent: true,
    dedupeKey: 'payment.receipt_uploaded:{{paymentId}}',
  },
  'payment.status_changed': {
    category: 'payments',
    severity: 'info',
    recipientType: 'store',
    title: 'تغيرت حالة الدفع',
    body: 'تغيرت حالة دفع الطلب {{orderCode}} من {{from}} إلى {{to}}.',
    actionUrl: '/merchant?tab=payments&paymentId={{paymentId}}',
    defaultFrequency: 'instant',
    isPersistent: true,
    dedupeKey: 'payment.status_changed:{{paymentId}}:{{to}}',
  },
  'payment.approved': {
    category: 'payments',
    severity: 'success',
    recipientType: 'store',
    title: 'تم تأكيد الدفع',
    body: 'تم تأكيد دفع الطلب {{orderCode}}.',
    actionUrl: '/merchant?tab=payments&paymentId={{paymentId}}',
    defaultFrequency: 'instant',
    isPersistent: true,
    dedupeKey: 'payment.approved:{{paymentId}}',
  },
  'payment.rejected': {
    category: 'payments',
    severity: 'critical',
    recipientType: 'store',
    title: 'تم رفض إيصال الدفع',
    body: 'تم رفض إيصال الدفع للطلب {{orderCode}}. يرجى مراجعة السبب.',
    actionUrl: '/merchant?tab=payments&paymentId={{paymentId}}',
    defaultFrequency: 'instant',
    isPersistent: true,
    dedupeKey: 'payment.rejected:{{paymentId}}',
  },
  'payment.reference_duplicate': {
    category: 'payments',
    severity: 'warning',
    recipientType: 'store',
    title: 'رقم مرجع مكرر',
    body: 'رقم المرجع المستخدم في الطلب {{orderCode}} موجود في عملية دفع أخرى.',
    actionUrl: '/merchant?tab=payments&paymentId={{paymentId}}',
    defaultFrequency: 'instant',
    isPersistent: true,
    dedupeKey: 'payment.reference_duplicate:{{storeId}}:{{referenceNumber}}',
  },
  'payment.receipt_missing_after_order': {
    category: 'payments',
    severity: 'warning',
    recipientType: 'store',
    title: 'طلب بانتظار إيصال الدفع',
    body: 'الطلب {{orderCode}} لم يتم رفع إيصال دفع له حتى الآن.',
    actionUrl: '/merchant?tab=payments&paymentId={{paymentId}}',
    defaultFrequency: 'daily_digest',
    isPersistent: true,
    dedupeKey: 'payment.receipt_missing_after_order:{{paymentId}}',
  },
  'inventory.low_stock': {
    category: 'inventory',
    severity: 'warning',
    recipientType: 'store',
    title: 'المخزون منخفض',
    body: 'المنتج {{productTitle}} وصل إلى {{currentStock}} فقط.',
    actionUrl: '/merchant?tab=inventory&variantId={{variantId}}',
    defaultFrequency: 'instant',
    isPersistent: true,
    dedupeKey: 'inventory.low_stock:{{variantId}}',
  },
  'inventory.back_in_stock': {
    category: 'inventory',
    severity: 'success',
    recipientType: 'store',
    title: 'تم إرسال تنبيهات توفر المخزون',
    body: 'تم إرسال {{sentCount}} تنبيه توفر مخزون، وفشل {{failedCount}}.',
    actionUrl: '/merchant?tab=restockAlerts',
    defaultFrequency: 'daily_digest',
    isPersistent: true,
    dedupeKey: 'inventory.back_in_stock:{{variantId}}',
  },
  'inventory.out_of_stock': {
    category: 'inventory',
    severity: 'critical',
    recipientType: 'store',
    title: 'نفد المخزون',
    body: 'المنتج {{productTitle}} أصبح غير متوفر.',
    actionUrl: '/merchant?tab=inventory&variantId={{variantId}}',
    defaultFrequency: 'instant',
    isPersistent: true,
    dedupeKey: 'inventory.out_of_stock:{{variantId}}',
  },
  'inventory.stock_restored': {
    category: 'inventory',
    severity: 'success',
    recipientType: 'store',
    title: 'تمت استعادة المخزون',
    body: 'عاد المنتج {{productTitle}} إلى المخزون.',
    actionUrl: '/merchant?tab=inventory&variantId={{variantId}}',
    defaultFrequency: 'instant',
    isPersistent: true,
    dedupeKey: 'inventory.stock_restored:{{variantId}}',
  },
  'inventory.stock_conflict_detected': {
    category: 'inventory',
    severity: 'critical',
    recipientType: 'store',
    title: 'تعارض في المخزون',
    body: 'تم اكتشاف تعارض بين مخزون المنتج والمستودعات للمنتج {{productTitle}}.',
    actionUrl: '/merchant?tab=inventory&variantId={{variantId}}',
    defaultFrequency: 'instant',
    isPersistent: true,
    dedupeKey: 'inventory.stock_conflict_detected:{{variantId}}',
  },
  'inventory.reservation_failed': {
    category: 'inventory',
    severity: 'warning',
    recipientType: 'store',
    title: 'فشل حجز المخزون',
    body: 'فشل حجز مخزون المنتج {{productTitle}} للطلب {{orderCode}}.',
    actionUrl: '/merchant?tab=inventory&variantId={{variantId}}',
    defaultFrequency: 'instant',
    isPersistent: true,
    dedupeKey: 'inventory.reservation_failed:{{variantId}}:{{orderId}}',
  },
  'inventory.bulk_update_completed': {
    category: 'inventory',
    severity: 'success',
    recipientType: 'store',
    title: 'اكتمل تحديث المخزون',
    body: 'اكتمل تحديث المخزون الجماعي بنجاح.',
    actionUrl: '/merchant?tab=inventory',
    defaultFrequency: 'daily_digest',
    isPersistent: true,
    dedupeKey: 'inventory.bulk_update_completed:{{batchId}}',
  },
  'cart.item_added': {
    category: 'cart',
    severity: 'info',
    recipientType: 'store',
    title: 'إضافة منتج للسلة',
    body: 'أضيف المنتج {{productTitle}} إلى سلة عميل.',
    actionUrl: '/merchant?tab=abandonedCarts&cartId={{cartId}}',
    defaultFrequency: 'mute',
    isPersistent: false,
    dedupeKey: 'cart.item_added:{{cartId}}:{{variantId}}',
  },
  'cart.high_value_detected': {
    category: 'cart',
    severity: 'warning',
    recipientType: 'store',
    title: 'سلة عالية القيمة',
    body: 'عميل أضاف منتجات بقيمة {{cartTotal}} {{currencyCode}} إلى السلة.',
    actionUrl: '/merchant?tab=abandonedCarts&cartId={{cartId}}',
    defaultFrequency: 'instant',
    isPersistent: true,
    dedupeKey: 'cart.high_value_detected:{{cartId}}',
  },
  'cart.strong_intent_detected': {
    category: 'cart',
    severity: 'info',
    recipientType: 'store',
    title: 'نية شراء عالية',
    body: 'عميل أضاف {{itemsCount}} منتجات إلى السلة.',
    actionUrl: '/merchant?tab=abandonedCarts&cartId={{cartId}}',
    defaultFrequency: 'daily_digest',
    isPersistent: true,
    dedupeKey: 'cart.strong_intent_detected:{{cartId}}',
  },
  'cart.abandoned_detected': {
    category: 'cart',
    severity: 'warning',
    recipientType: 'store',
    title: 'سلة مهجورة مهمة',
    body: 'عميل ترك سلة بقيمة {{cartTotal}} {{currencyCode}}.',
    actionUrl: '/merchant?tab=abandonedCarts&cartId={{cartId}}',
    defaultFrequency: 'daily_digest',
    isPersistent: true,
    dedupeKey: 'cart.abandoned_detected:{{cartId}}',
  },
  'cart.recovered': {
    category: 'cart',
    severity: 'success',
    recipientType: 'store',
    title: 'تم استرجاع سلة مهجورة',
    body: 'تحولت سلة مهجورة إلى طلب جديد {{orderCode}}.',
    actionUrl: '/merchant?tab=orders&orderId={{orderId}}',
    defaultFrequency: 'instant',
    isPersistent: true,
    dedupeKey: 'cart.recovered:{{cartId}}:{{orderId}}',
  },
  'checkout.failed': {
    category: 'checkout',
    severity: 'warning',
    recipientType: 'store',
    title: 'فشل إتمام الطلب',
    body: 'عميل حاول إتمام الطلب ولم تنجح العملية.',
    actionUrl: '/merchant?tab=abandonedCarts&cartId={{cartId}}',
    defaultFrequency: 'daily_digest',
    isPersistent: true,
    dedupeKey: 'checkout.failed:{{cartId}}:{{reason}}',
  },
  'domain.verified': {
    category: 'domain',
    severity: 'success',
    recipientType: 'store',
    title: 'تم التحقق من الدومين',
    body: 'تم التحقق من إعدادات الدومين {{domain}} بنجاح.',
    actionUrl: '/merchant?tab=domains&domainId={{domainId}}',
    defaultFrequency: 'instant',
    isPersistent: true,
    dedupeKey: 'domain.verified:{{domainId}}',
  },
  'domain.activated': {
    category: 'domain',
    severity: 'success',
    recipientType: 'store',
    title: 'تم تفعيل الدومين',
    body: 'أصبح الدومين {{domain}} يعمل على المتجر.',
    actionUrl: '/merchant?tab=domains&domainId={{domainId}}',
    defaultFrequency: 'instant',
    isPersistent: true,
    dedupeKey: 'domain.activated:{{domainId}}',
  },
  'domain.verification_failed': {
    category: 'domain',
    severity: 'warning',
    recipientType: 'store',
    title: 'تعذر التحقق من الدومين',
    body: 'الدومين {{domain}} يحتاج مراجعة إعدادات التحقق.',
    actionUrl: '/merchant?tab=domains&domainId={{domainId}}',
    defaultFrequency: 'instant',
    isPersistent: true,
    dedupeKey: 'domain.verification_failed:{{domainId}}',
  },
  'domain.ssl_error': {
    category: 'domain',
    severity: 'critical',
    recipientType: 'store',
    title: 'مشكلة في شهادة الدومين',
    body: 'الدومين {{domain}} لديه مشكلة SSL وتحتاج مراجعة.',
    actionUrl: '/merchant?tab=domains&domainId={{domainId}}',
    defaultFrequency: 'instant',
    isPersistent: true,
    dedupeKey: 'domain.ssl_error:{{domainId}}',
  },
  'domain.dns_misconfigured': {
    category: 'domain',
    severity: 'warning',
    recipientType: 'store',
    title: 'مشكلة في الدومين',
    body: 'الدومين {{domain}} يحتاج مراجعة إعدادات DNS.',
    actionUrl: '/merchant?tab=domains&domainId={{domainId}}',
    defaultFrequency: 'instant',
    isPersistent: true,
    dedupeKey: 'domain.dns_misconfigured:{{domainId}}',
  },
  'support.ticket.created': {
    category: 'support',
    severity: 'warning',
    recipientType: 'store',
    title: 'تذكرة دعم جديدة',
    body: '{{subject}}',
    actionUrl: '/merchant?tab=supportTickets&ticketId={{ticketId}}',
    defaultFrequency: 'instant',
    isPersistent: true,
    dedupeKey: 'support.ticket.created:{{ticketId}}',
  },
  'support.ticket.updated': {
    category: 'support',
    severity: 'info',
    recipientType: 'store',
    title: 'تحديث على تذكرة دعم',
    body: '{{subject}}',
    actionUrl: '/merchant?tab=supportTickets&ticketId={{ticketId}}',
    defaultFrequency: 'instant',
    isPersistent: true,
    dedupeKey: 'support.ticket.updated:{{ticketId}}:{{messageId}}',
  },
  'support.ticket.assigned': {
    category: 'support',
    severity: 'info',
    recipientType: 'store_user',
    title: 'تم إسناد تذكرة دعم',
    body: '{{subject}}',
    actionUrl: '/merchant?tab=supportTickets&ticketId={{ticketId}}',
    defaultFrequency: 'instant',
    isPersistent: true,
    dedupeKey: 'support.ticket.assigned:{{ticketId}}:{{assigneeId}}',
  },
  'support.ticket.escalated': {
    category: 'support',
    severity: 'critical',
    recipientType: 'store',
    title: 'تم تصعيد تذكرة دعم',
    body: '{{subject}}',
    actionUrl: '/merchant?tab=supportTickets&ticketId={{ticketId}}',
    defaultFrequency: 'instant',
    isPersistent: true,
    dedupeKey: 'support.ticket.escalated:{{ticketId}}',
  },
  'support.ticket.sla_breached': {
    category: 'support',
    severity: 'critical',
    recipientType: 'store',
    title: 'تجاوز اتفاقية مستوى الخدمة',
    body: 'تذكرة الدعم {{subject}} تجاوزت وقت الاستجابة المطلوب.',
    actionUrl: '/merchant?tab=supportTickets&ticketId={{ticketId}}',
    defaultFrequency: 'instant',
    isPersistent: true,
    dedupeKey: 'support.ticket.sla_breached:{{ticketId}}',
  },
  'analytics.anomaly_detected': {
    category: 'analytics',
    severity: 'warning',
    recipientType: 'store',
    title: 'تنبيه تحليلي',
    body: '{{message}}',
    actionUrl: '/merchant?tab=analytics',
    defaultFrequency: 'instant',
    isPersistent: true,
    dedupeKey: 'analytics.anomaly_detected:{{storeId}}:{{anomalyType}}',
  },
  'notification.delivery.failed': {
    category: 'system',
    severity: 'critical',
    recipientType: 'store',
    title: 'فشل تسليم إشعار',
    body: '{{errorMessage}}',
    actionUrl: '/merchant?tab=notificationsCenter',
    defaultFrequency: 'instant',
    isPersistent: true,
    dedupeKey: 'notification.delivery.failed:{{eventType}}:{{attempts}}',
  },
  'customer.order.created': {
    category: 'orders',
    severity: 'success',
    recipientType: 'customer',
    title: 'تم استلام طلبك',
    body: 'تم استلام طلبك {{orderCode}} بقيمة {{total}} {{currencyCode}}.',
    actionUrl: '/account?tab=orders',
    defaultFrequency: 'instant',
    isPersistent: true,
    dedupeKey: 'customer.order.created:{{customerId}}:{{orderId}}',
  },
  'customer.order.updated': {
    category: 'orders',
    severity: 'info',
    recipientType: 'customer',
    title: 'تم تحديث طلبك',
    body: 'تم تحديث بيانات طلبك {{orderCode}}.',
    actionUrl: '/account?tab=orders',
    defaultFrequency: 'instant',
    isPersistent: true,
    dedupeKey: 'customer.order.updated:{{customerId}}:{{orderId}}',
  },
  'customer.order.status.changed': {
    category: 'orders',
    severity: 'info',
    recipientType: 'customer',
    title: 'تغيرت حالة طلبك',
    body: 'تغيرت حالة طلبك {{orderCode}} إلى {{to}}.',
    actionUrl: '/account?tab=orders',
    defaultFrequency: 'instant',
    isPersistent: true,
    dedupeKey: 'customer.order.status.changed:{{customerId}}:{{orderId}}:{{to}}',
  },
  'customer.payment.status_changed': {
    category: 'payments',
    severity: 'info',
    recipientType: 'customer',
    title: 'تغيرت حالة الدفع',
    body: 'تغيرت حالة دفع الطلب {{orderCode}} إلى {{to}}.',
    actionUrl: '/account?tab=orders',
    defaultFrequency: 'instant',
    isPersistent: true,
    dedupeKey: 'customer.payment.status_changed:{{customerId}}:{{paymentId}}:{{to}}',
  },
} satisfies Record<string, RegistryDefinitionInput>);

export type MerchantNotificationEventType = keyof typeof MERCHANT_NOTIFICATION_EVENTS;

export const MERCHANT_NOTIFICATION_CATEGORIES: MerchantNotificationCategory[] = [
  'orders',
  'payments',
  'inventory',
  'cart',
  'checkout',
  'support',
  'domain',
  'analytics',
  'system',
];

export const MERCHANT_NOTIFICATION_SEVERITIES: MerchantNotificationSeverity[] = [
  'info',
  'success',
  'warning',
  'critical',
];

export function getMerchantNotificationEvent(
  eventType: string,
): MerchantNotificationEventDefinition | undefined {
  return MERCHANT_NOTIFICATION_EVENTS[eventType as MerchantNotificationEventType];
}

export function listMerchantNotificationEvents(): MerchantNotificationEventDefinition[] {
  return Object.values(MERCHANT_NOTIFICATION_EVENTS);
}
