import { useEffect, useState } from 'react';
import { brandConfig } from './config/brand.config';
import { pageFromLocation, pathForPage, type Page } from './navigation';
import { HomePage } from './pages/HomePage';
import { CatalogPage } from './pages/CatalogPage';
import { ProductPage } from './pages/ProductPage';
import { QuoteCartPage } from './pages/QuoteCartPage';
import { QuoteTrackingPage } from './pages/QuoteTrackingPage';
type Lang='ar'|'en';
export function App(){const[page,setPage]=useState<Page>(()=>pageFromLocation()),[lang,setLang]=useState<Lang>(()=>(localStorage.getItem('catalog-lang') as Lang)||'ar'),[menu,setMenu]=useState(false);
  useEffect(()=>{const pop=()=>setPage(pageFromLocation());window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop);},[]);
  const navigate=(next:Page,replace=false)=>{const path=pathForPage(next);history[replace?'replaceState':'pushState']({},'',path);setPage(next);setMenu(false);window.scrollTo({top:0,behavior:'smooth'});};
  const toggle=()=>{const next=lang==='ar'?'en':'ar';setLang(next);localStorage.setItem('catalog-lang',next);};
  return <div dir={lang==='ar'?'rtl':'ltr'} lang={lang}><header className="header"><div className="container header-row"><button className="logo" onClick={()=>navigate({name:'home'})}><span className="logo-mark">M</span><span>{lang==='ar'?brandConfig.nameAr:brandConfig.nameEn}</span></button><button className="menu-button" onClick={()=>setMenu(!menu)}>☰</button><nav className={'nav '+(menu?'open':'')}><button onClick={()=>navigate({name:'home'})}>{lang==='ar'?'الرئيسية':'Home'}</button><button onClick={()=>navigate({name:'catalog'})}>{lang==='ar'?'الكتالوج':'Catalog'}</button><button onClick={()=>navigate({name:'tracking'})}>{lang==='ar'?'تتبع الطلب':'Track request'}</button><button onClick={toggle}>{lang==='ar'?'EN':'العربية'}</button><button className="cart-button" onClick={()=>navigate({name:'cart'})}>{lang==='ar'?'طلب عرض':'Quote cart'}</button></nav></div></header>
    {page.name==='home'&&<HomePage lang={lang} navigate={navigate}/>} {page.name==='catalog'&&<CatalogPage lang={lang} page={page} navigate={navigate}/>} {page.name==='product'&&<ProductPage lang={lang} page={page} navigate={navigate}/>} {page.name==='cart'&&<QuoteCartPage lang={lang} navigate={navigate}/>} {page.name==='tracking'&&<QuoteTrackingPage lang={lang} page={page}/>} {page.name==='success'&&<Success lang={lang} data={page.data} navigate={navigate}/>} {page.name==='static'&&<StaticPage lang={lang} pageKey={page.key}/>}<Footer lang={lang} navigate={navigate}/></div>;}
function Success({lang,data,navigate}:{lang:Lang;data?:Record<string,any>;navigate:(page:Page)=>void}){return <main className="container success-page"><div className="success-icon">✓</div><h1>{lang==='ar'?'تم إرسال طلبك':'Request submitted'}</h1><p>{lang==='ar'?'رقم الطلب':'Request number'}: <strong>{data?.requestNumber}</strong></p>{data?.trackingToken&&<button className="button" onClick={()=>navigate({name:'tracking',requestNumber:data.requestNumber,token:data.trackingToken})}>{lang==='ar'?'تتبع الطلب':'Track request'}</button>}</main>;}
function StaticPage({lang,pageKey}:{lang:Lang;pageKey:string}){const labels:Record<string,[string,string]>={about:['عن المرهمي','About Al Marhomy'],contact:['تواصل معنا','Contact us'],privacy:['سياسة الخصوصية','Privacy policy'],terms:['الشروط والأحكام','Terms'],faq:['الأسئلة الشائعة','FAQ']};return <main className="container section static-page"><h1>{labels[pageKey]?.[lang==='ar'?0:1]??pageKey}</h1><p>{lang==='ar'?'هذا الكتالوج مخصص لاختيار موديلات المعدات وإرسال طلب عرض سعر دون دفع أو أسعار وهمية.':'This catalog is for selecting equipment models and sending quote requests, without checkout or placeholder prices.'}</p></main>;}
function Footer({lang,navigate}:{lang:Lang;navigate:(page:Page)=>void}){return <footer className="footer"><div className="container footer-grid"><div><h2>{lang==='ar'?brandConfig.nameAr:brandConfig.nameEn}</h2><p>{lang==='ar'?brandConfig.taglineAr:brandConfig.taglineEn}</p></div><div><h3>{lang==='ar'?'الكتالوج':'Catalog'}</h3><button onClick={()=>navigate({name:'catalog'})}>{lang==='ar'?'جميع المنتجات':'All products'}</button><button onClick={()=>navigate({name:'tracking'})}>{lang==='ar'?'تتبع طلب':'Track request'}</button></div><div><h3>{lang==='ar'?'روابط':'Links'}</h3><button onClick={()=>navigate({name:'static',key:'about'})}>{lang==='ar'?'عن الشركة':'About'}</button><button onClick={()=>navigate({name:'static',key:'contact'})}>{lang==='ar'?'تواصل معنا':'Contact'}</button></div></div></footer>;}
