import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { api } from '../../api';
type Row=Record<string,any>;
function flatten(rows:Row[],depth=0):Row[]{return rows.flatMap(row=>[{...row,depth},...flatten(row.children??[],depth+1)]);}
const empty={titleAr:'',titleEn:'',slug:'',parentId:'',catalogCode:'',descriptionAr:'',descriptionEn:'',imageUrl:'',logoUrl:'',isActive:true,sortOrder:0,specificationIds:[] as string[]};
export function CatalogManager({kind,canWrite}:{kind:'categories'|'brands';canWrite:boolean}){
  const[data,setData]=useState<Row[]>([]),[editing,setEditing]=useState<Row|null>(null),[definitions,setDefinitions]=useState<Row[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true);
  const load=useCallback(async()=>{setLoading(true);try{const rows=await api<Row[]>(`/admin/${kind}`);setData(kind==='categories'?flatten(rows):rows);}catch(value){setError((value as Error).message);}finally{setLoading(false);}},[kind]);
  useEffect(()=>{void load();if(kind==='categories')api<Row[]>('/admin/specifications').then(setDefinitions).catch(()=>setDefinitions([]));},[load,kind]);
  const start=async(row?:Row)=>{const form=row?{...empty,id:row.id,titleAr:row.title_ar,titleEn:row.title_en??'',slug:row.slug,parentId:row.parent_id??'',catalogCode:row.catalog_code??'',descriptionAr:row.description_ar??'',descriptionEn:row.description_en??'',imageUrl:row.image_url??'',logoUrl:row.logo_url??'',isActive:row.is_active,sortOrder:row.sort_order,specificationIds:[]}: {...empty};
    if(row&&kind==='categories'){const specs=await api<Row[]>(`/admin/categories/${row.id}/specifications`);form.specificationIds=specs.filter(spec=>spec.category_id===row.id).map(spec=>spec.id);}setEditing(form);};
  const remove=async(row:Row)=>{if(!window.confirm(`حذف ${row.title_ar}؟`))return;try{await api(`/admin/${kind}/${row.id}`,{method:'DELETE'});await load();}catch(value){setError((value as Error).message);}};
  const move=async(index:number,direction:number)=>{if(kind!=='categories')return;const current=data[index],target=index+direction;if(!current||target<0||target>=data.length)return;const ids=data.filter(row=>row.parent_id===current.parent_id).map(row=>row.id);const local=ids.indexOf(current.id),swap=local+direction;if(swap<0||swap>=ids.length)return;[ids[local],ids[swap]]=[ids[swap]!,ids[local]!];await api('/admin/categories/reorder',{method:'PATCH',body:JSON.stringify({categoryIds:ids})});await load();};
  return <><div className="page-head"><div><h1>{kind==='categories'?'شجرة الأقسام':'العلامات التجارية'}</h1><p>{kind==='categories'?'هيكل غير محدود وربط نموذج المواصفات بكل قسم.':'إدارة علامات الكتالوج.'}</p></div>{canWrite&&<button className="button" onClick={()=>void start()}>إضافة</button>}</div>{error&&<div className="error">{error}</div>}
    <div className="table-wrap">{loading?<div className="empty">جارٍ التحميل…</div>:<table><thead><tr><th>الاسم</th><th>Slug</th>{kind==='categories'&&<th>كود PART</th>}<th>الحالة</th><th></th></tr></thead><tbody>{data.map((row,index)=><tr key={row.id}><td><strong>{'— '.repeat(row.depth??0)}{row.title_ar}</strong><div className="muted">{row.title_en}</div></td><td>{row.slug}</td>{kind==='categories'&&<td>{row.catalog_code??'—'}</td>}<td>{row.is_active?'فعال':'معطل'}</td><td>{canWrite&&<div className="mini-actions"><button onClick={()=>void start(row)}>تعديل</button>{kind==='categories'&&<><button onClick={()=>void move(index,-1)}>↑</button><button onClick={()=>void move(index,1)}>↓</button></>}<button className="danger-text" onClick={()=>void remove(row)}>حذف</button></div>}</td></tr>)}</tbody></table>}</div>
    {editing&&<CatalogDialog kind={kind} form={editing} rows={data} definitions={definitions} close={()=>setEditing(null)} saved={async()=>{setEditing(null);await load();}}/>}</>;
}
function CatalogDialog({kind,form:initial,rows,definitions,close,saved}:{kind:'categories'|'brands';form:Row;rows:Row[];definitions:Row[];close:()=>void;saved:()=>Promise<void>}){
  const[form,setForm]=useState(initial),[error,setError]=useState('');const change=(key:string,value:any)=>setForm((current:Row)=>({...current,[key]:value}));
  const submit=async(event:FormEvent)=>{event.preventDefault();try{const body=kind==='categories'?{titleAr:form.titleAr,titleEn:form.titleEn||null,slug:form.slug,parentId:form.parentId||null,catalogCode:form.catalogCode||null,descriptionAr:form.descriptionAr||null,descriptionEn:form.descriptionEn||null,imageUrl:form.imageUrl||null,isActive:form.isActive,sortOrder:Number(form.sortOrder)}:{titleAr:form.titleAr,titleEn:form.titleEn||null,slug:form.slug,descriptionAr:form.descriptionAr||null,descriptionEn:form.descriptionEn||null,logoUrl:form.logoUrl||null,isActive:form.isActive,sortOrder:Number(form.sortOrder)};
    const result=await api<Row>(`/admin/${kind}${form.id?'/'+form.id:''}`,{method:form.id?'PATCH':'POST',body:JSON.stringify(body)});if(kind==='categories')await api(`/admin/categories/${result.id}/specifications`,{method:'PUT',body:JSON.stringify({values:form.specificationIds.map((specificationId:string,index:number)=>({specificationId,sortOrder:index}))})});await saved();}catch(value){setError((value as Error).message);}};
  return <div className="dialog-backdrop"><form className="dialog catalog-dialog" onSubmit={submit}><div className="dialog-head"><h2>{form.id?'تعديل':'إضافة'} {kind==='categories'?'قسم':'علامة'}</h2><button type="button" className="close" onClick={close}>×</button></div>{error&&<div className="error">{error}</div>}<div className="form-grid"><label className="field"><span>الاسم بالعربية</span><input required value={form.titleAr} onChange={event=>change('titleAr',event.target.value)}/></label><label className="field"><span>الاسم بالإنجليزية</span><input value={form.titleEn} onChange={event=>change('titleEn',event.target.value)}/></label><label className="field"><span>Slug</span><input required value={form.slug} onChange={event=>change('slug',event.target.value)}/></label><label className="field"><span>الترتيب</span><input type="number" value={form.sortOrder} onChange={event=>change('sortOrder',event.target.value)}/></label>
    {kind==='categories'&&<><label className="field"><span>القسم الأب</span><select value={form.parentId} onChange={event=>change('parentId',event.target.value)}><option value="">قسم رئيسي</option>{rows.filter(row=>row.id!==form.id).map(row=><option key={row.id} value={row.id}>{'— '.repeat(row.depth??0)}{row.title_ar}</option>)}</select></label><label className="field"><span>كود PART</span><input value={form.catalogCode} onChange={event=>change('catalogCode',event.target.value)}/></label><label className="field"><span>رابط الصورة</span><input value={form.imageUrl} onChange={event=>change('imageUrl',event.target.value)}/></label><fieldset className="choice-list full"><legend>مواصفات القسم</legend>{definitions.map(definition=><label key={definition.id}><input type="checkbox" checked={form.specificationIds.includes(definition.id)} onChange={event=>change('specificationIds',event.target.checked?[...form.specificationIds,definition.id]:form.specificationIds.filter((id:string)=>id!==definition.id))}/>{definition.name_ar} ({definition.value_type})</label>)}</fieldset></>}
    {kind==='brands'&&<label className="field"><span>رابط الشعار</span><input value={form.logoUrl} onChange={event=>change('logoUrl',event.target.value)}/></label>}<label className="field full"><span>الوصف بالعربية</span><textarea rows={3} value={form.descriptionAr} onChange={event=>change('descriptionAr',event.target.value)}/></label><label className="field full"><span>الوصف بالإنجليزية</span><textarea dir="ltr" rows={3} value={form.descriptionEn} onChange={event=>change('descriptionEn',event.target.value)}/></label><label className="field check"><input type="checkbox" checked={form.isActive} onChange={event=>change('isActive',event.target.checked)}/> فعال</label></div><div className="dialog-actions"><button className="button">حفظ</button><button type="button" className="button secondary" onClick={close}>إلغاء</button></div></form></div>;
}
