import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { api } from '../../api';
type Row=Record<string,any>;
const empty={slug:'',nameAr:'',nameEn:'',valueType:'text',unitAr:'',unitEn:'',isRequiredDefault:false,isFilterable:false,isComparable:true,isActive:true,sortOrder:0,options:[] as Row[]};
export function SpecificationsManager({canWrite}:{canWrite:boolean}){const[rows,setRows]=useState<Row[]>([]),[editing,setEditing]=useState<Row|null>(null),[error,setError]=useState('');const load=useCallback(async()=>{try{setRows(await api<Row[]>('/admin/specifications'));}catch(value){setError((value as Error).message);}},[]);useEffect(()=>{void load();},[load]);
  const start=(row?:Row)=>setEditing(row?{id:row.id,slug:row.slug,nameAr:row.name_ar,nameEn:row.name_en??'',valueType:row.value_type,unitAr:row.unit_ar??'',unitEn:row.unit_en??'',isRequiredDefault:row.is_required_default,isFilterable:row.is_filterable,isComparable:row.is_comparable,isActive:row.is_active,sortOrder:row.sort_order,options:(row.options??[]).map((option:Row)=>({valueKey:option.value_key,labelAr:option.label_ar,labelEn:option.label_en??'',sortOrder:option.sort_order,isActive:option.is_active}))}:{...empty,options:[]});
  return <><div className="page-head"><div><h1>تعريفات المواصفات</h1><p>مصدر واحد للمواصفات والفلاتر والمقارنة.</p></div>{canWrite&&<button className="button" onClick={()=>start()}>إضافة مواصفة</button>}</div>{error&&<div className="error">{error}</div>}<div className="table-wrap"><table><thead><tr><th>الاسم</th><th>Slug</th><th>النوع</th><th>الوحدة</th><th>فلترة</th><th>مقارنة</th><th></th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{row.name_ar}</strong><div className="muted">{row.name_en}</div></td><td>{row.slug}</td><td>{row.value_type}</td><td>{row.unit_ar??'—'}</td><td>{row.is_filterable?'نعم':'لا'}</td><td>{row.is_comparable?'نعم':'لا'}</td><td>{canWrite&&<div className="mini-actions"><button onClick={()=>start(row)}>تعديل</button><button className="danger-text" onClick={async()=>{if(window.confirm('حذف المواصفة؟')){await api('/admin/specifications/'+row.id,{method:'DELETE'});await load();}}}>حذف</button></div>}</td></tr>)}</tbody></table></div>{editing&&<SpecificationDialog form={editing} close={()=>setEditing(null)} saved={async()=>{setEditing(null);await load();}}/>}</>;
}
function SpecificationDialog({form:initial,close,saved}:{form:Row;close:()=>void;saved:()=>Promise<void>}){const[form,setForm]=useState(initial),[error,setError]=useState('');const change=(key:string,value:any)=>setForm((current:Row)=>({...current,[key]:value}));const submit=async(event:FormEvent)=>{event.preventDefault();try{await api('/admin/specifications'+(form.id?'/'+form.id:''),{method:form.id?'PATCH':'POST',body:JSON.stringify({...form,nameEn:form.nameEn||null,unitAr:form.unitAr||null,unitEn:form.unitEn||null})});await saved();}catch(value){setError((value as Error).message);}};
  return <div className="dialog-backdrop"><form className="dialog" onSubmit={submit}><div className="dialog-head"><h2>تعريف المواصفة</h2><button type="button" className="close" onClick={close}>×</button></div>{error&&<div className="error">{error}</div>}<div className="form-grid"><label className="field"><span>الاسم بالعربية</span><input required value={form.nameAr} onChange={event=>change('nameAr',event.target.value)}/></label><label className="field"><span>الاسم بالإنجليزية</span><input value={form.nameEn} onChange={event=>change('nameEn',event.target.value)}/></label><label className="field"><span>Slug</span><input required value={form.slug} onChange={event=>change('slug',event.target.value)}/></label><label className="field"><span>النوع</span><select value={form.valueType} onChange={event=>change('valueType',event.target.value)}><option value="text">نص</option><option value="number">رقم</option><option value="range">مدى</option><option value="option">خيارات</option><option value="boolean">نعم/لا</option></select></label><label className="field"><span>الوحدة عربي</span><input value={form.unitAr} onChange={event=>change('unitAr',event.target.value)}/></label><label className="field"><span>Unit English</span><input value={form.unitEn} onChange={event=>change('unitEn',event.target.value)}/></label><label className="field check"><input type="checkbox" checked={form.isFilterable} onChange={event=>change('isFilterable',event.target.checked)}/> قابلة للفلترة</label><label className="field check"><input type="checkbox" checked={form.isComparable} onChange={event=>change('isComparable',event.target.checked)}/> قابلة للمقارنة</label><label className="field check"><input type="checkbox" checked={form.isRequiredDefault} onChange={event=>change('isRequiredDefault',event.target.checked)}/> مطلوبة افتراضيًا</label></div>
    {form.valueType==='option'&&<section className="editor-section"><div className="section-head"><h3>الخيارات</h3><button type="button" className="button secondary small" onClick={()=>change('options',[...form.options,{valueKey:'',labelAr:'',labelEn:'',sortOrder:form.options.length,isActive:true}])}>إضافة خيار</button></div>{form.options.map((option:Row,index:number)=><div className="row-editor" key={index}><input placeholder="المفتاح" value={option.valueKey} onChange={event=>change('options',form.options.map((item:Row,i:number)=>i===index?{...item,valueKey:event.target.value}:item))}/><input placeholder="العربية" value={option.labelAr} onChange={event=>change('options',form.options.map((item:Row,i:number)=>i===index?{...item,labelAr:event.target.value}:item))}/><input placeholder="English" value={option.labelEn} onChange={event=>change('options',form.options.map((item:Row,i:number)=>i===index?{...item,labelEn:event.target.value}:item))}/><button type="button" className="danger-text" onClick={()=>change('options',form.options.filter((_:Row,i:number)=>i!==index))}>حذف</button></div>)}</section>}
    <div className="dialog-actions"><button className="button">حفظ</button><button type="button" className="button secondary" onClick={close}>إلغاء</button></div></form></div>;
}
