const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const root=path.resolve(__dirname,'..');
function files(directory){return fs.readdirSync(directory,{withFileTypes:true}).flatMap(entry=>entry.isDirectory()?files(path.join(directory,entry.name)):[path.join(directory,entry.name)]);}
function source(){return files(path.join(root,'src')).filter(file=>/\.(ts|tsx|sql)$/.test(file)).map(file=>fs.readFileSync(file,'utf8')).join('\n');}
function migrations(){return files(path.join(root,'migrations')).filter(file=>file.endsWith('.up.sql')).map(file=>fs.readFileSync(file,'utf8')).join('\n');}
test('backend contains the final multi-model RFQ modules',()=>{const directories=fs.readdirSync(path.join(root,'src'),{withFileTypes:true}).filter(entry=>entry.isDirectory()).map(entry=>entry.name).sort();assert.deepEqual(directories,['analytics','audit','auth','catalog','catalog-import','common','config','database','email','health','media','notifications','outbox','products','quote-carts','quote-requests','rbac','seo','team','types','workers']);});
test('source has no financial, fulfillment, or stock domain remnants',()=>{const content=source();for(const fragment of ['store'+'_id','ten'+'ant','pri'+'ce','curr'+'ency','sub'+'total','dis'+'count','t'+'ax','inven'+'tory','ware'+'house','ship'+'ment','pay'+'ment','cou'+'pon'])assert.equal(content.toLowerCase().includes(fragment),false,'found '+fragment);});
test('baseline consists of ten ordered reversible migrations',()=>{const names=fs.readdirSync(path.join(root,'migrations'));const up=names.filter(name=>name.endsWith('.up.sql')).sort(),down=names.filter(name=>name.endsWith('.down.sql')).sort();assert.equal(up.length,10);assert.equal(down.length,10);assert.deepEqual(up.map(name=>name.slice(0,3)),['001','002','003','004','005','006','007','008','009','010']);for(const name of up)assert.ok(names.includes(name.replace('.up.sql','.down.sql')));});
test('catalog separates general products from requestable models and specifications',()=>{const catalog=fs.readFileSync(path.join(root,'migrations','002_create_catalog_core.up.sql'),'utf8'),models=fs.readFileSync(path.join(root,'migrations','003_create_product_models_and_specifications.up.sql'),'utf8');assert.doesNotMatch(catalog,/model_code|minimum_request_quantity|specifications JSONB/);for(const phrase of ['CREATE TABLE product_models','model_code','availability_status','product_model_images','specification_definitions','category_specifications','product_model_specification_values'])assert.match(models,new RegExp(phrase));assert.match(models,/NUMERIC\(14,3\)/);});
test('legacy catalog tables and contracts are absent from the baseline',()=>{const sql=migrations().toLowerCase();for(const name of ['product_'+'variants','attribute_'+'values','category_'+'attributes','product_'+'filter_'+'values','selected_'+'options'])assert.equal(sql.includes(name),false,name);});
test('cart and request items retain model identity and immutable snapshots',()=>{const carts=fs.readFileSync(path.join(root,'migrations','004_create_quote_carts.up.sql'),'utf8'),requests=fs.readFileSync(path.join(root,'migrations','005_create_quote_requests.up.sql'),'utf8');assert.match(carts,/model_id UUID NOT NULL REFERENCES product_models\(id\) ON DELETE RESTRICT/);assert.match(carts,/UNIQUE \(quote_cart_id, model_id\)/);assert.match(requests,/model_id UUID REFERENCES product_models\(id\) ON DELETE SET NULL/);for(const field of ['model_code_snapshot','specifications_snapshot','availability_snapshot','quantity_rules_snapshot'])assert.ok(requests.includes(field));});
test('analytics and maintenance remain independent of live catalog rows',()=>{const analytics=fs.readFileSync(path.join(root,'src','analytics','analytics.service.ts'),'utf8'),schema=fs.readFileSync(path.join(root,'migrations','004_create_quote_carts.up.sql'),'utf8');assert.match(schema,/is_suspicious BOOLEAN/);assert.match(schema,/archived_at TIMESTAMPTZ/);assert.match(analytics,/NOT is_suspicious/);assert.match(analytics,/product_title_snapshot/);assert.doesNotMatch(analytics,/JOIN products p ON p\.id=i\.product_id JOIN categories/);});
