import { useEffect, useState, type FormEvent } from 'react';
import { api } from '../../api';
type Row=Record<string,any>;
type ModelImage={imageUrl:string;altTextAr:string;altTextEn:string;isPrimary:boolean;sortOrder:number};
function Field({label,value,onChange,type='text',step}:{label:string;value:any;onChange:(value:string)=>void;type?:string;step?:string}){return <label className="field"><span>{label}</span><input type={type} step={step} value={value??''} onChange={event=>onChange(event.target.value)}/></label>;}
export function ModelEditorDrawer({productId,categoryId,model,close,saved}:{productId:string;categoryId:string;model:Row;close:()=>void;saved:()=>Promise<void>}){
  const[definitions,setDefinitions]=useState<Row[]>([]),[error,setError]=useState(''),[saving,setSaving]=useState(false),[tab,setTab]=useState('basic');
  const[form,setForm]=useState(()=>({modelCode:model.model_code??'',titleAr:model.title_ar??'',titleEn:model.title_en??'',sku:model.sku??'',barcode:model.barcode??'',descriptionAr:model.description_ar??'',descriptionEn:model.description_en??'',availabilityStatus:model.availability_status??'available',quoteEnabled:model.quote_enabled??true,unitOfMeasure:model.unit_of_measure??'piece',minimumRequestQuantity:Number(model.minimum_request_quantity??1),maximumRequestQuantity:model.maximum_request_quantity??'',quantityStep:Number(model.quantity_step??1),datasheetUrl:model.datasheet_url??'',manualUrl:model.manual_url??'',videoUrl:model.video_url??'',isDefault:model.is_default??false,isActive:model.is_active??true,sortOrder:Number(model.sort_order??0)}));
  const[images,setImages]=useState<ModelImage[]>(()=>(model.images??[]).map((image:Row,index:number)=>({imageUrl:image.image_url,altTextAr:image.alt_text_ar??'',altTextEn:image.alt_text_en??'',isPrimary:image.is_primary??index===0,sortOrder:index})));
  const[values,setValues]=useState<Record<string,Row>>(()=>Object.fromEntries((model.specifications??[]).map((value:Row)=>[value.specification_id,{textAr:value.value_text_ar??value.display_value_ar??'',textEn:value.value_text_en??value.display_value_en??'',number:value.value_number??'',to:value.value_number_to??'',boolean:value.value_boolean??false,optionId:value.option_id??''}])));
  useEffect(()=>{api<Row[]>(`/admin/categories/${categoryId}/specifications`).then(setDefinitions).catch(value=>setError((value as Error).message));},[categoryId]);const change=(key:string,value:any)=>setForm(current=>({...current,[key]:value}));
  const changeSpec=(id:string,patch:Row)=>setValues(current=>({...current,[id]:{...(current[id]??{}),...patch}}));
  const submit=async(event:FormEvent)=>{event.preventDefault();setSaving(true);setError('');try{const specs=definitions.map(definition=>{const value=values[definition.id]??{},common={specificationId:definition.id,sortOrder:definition.sort_order??0};if(definition.value_type==='number')return{...common,valueNumber:value.number===''?null:Number(value.number),displayValueAr:String(value.number??''),displayValueEn:String(value.number??'')};if(definition.value_type==='range')return{...common,valueNumber:value.number===''?null:Number(value.number),valueNumberTo:value.to===''?null:Number(value.to),displayValueAr:`${value.number}–${value.to}`,displayValueEn:`${value.number}–${value.to}`};if(definition.value_type==='boolean')return{...common,valueBoolean:Boolean(value.boolean),displayValueAr:value.boolean?'نعم':'لا',displayValueEn:value.boolean?'Yes':'No'};if(definition.value_type==='option')return{...common,optionId:value.optionId||null};return{...common,valueTextAr:value.textAr||null,valueTextEn:value.textEn||null,displayValueAr:value.textAr||null,displayValueEn:value.textEn||null};}).filter(value=>Object.values(value).some(item=>item!==null&&item!==''));
    const body={...form,titleAr:form.titleAr||null,titleEn:form.titleEn||null,sku:form.sku||null,barcode:form.barcode||null,descriptionAr:form.descriptionAr||null,descriptionEn:form.descriptionEn||null,maximumRequestQuantity:form.maximumRequestQuantity===''?null:Number(form.maximumRequestQuantity),datasheetUrl:form.datasheetUrl||null,manualUrl:form.manualUrl||null,videoUrl:form.videoUrl||null,images:images.filter(image=>image.imageUrl).map((image,index)=>({...image,sortOrder:index})),specifications:specs};await api(model.id?`/admin/products/${productId}/models/${model.id}`:`/admin/products/${productId}/models`,{method:model.id?'PATCH':'POST',body:JSON.stringify(body)});await saved();}
    catch(value){setError((value as Error).message);}finally{setSaving(false);}};
  return <div className="nested-dialog"><form className="dialog model-dialog" onSubmit={submit}><div className="dialog-head"><div><h2>{model.id?'تعديل الموديل':'إضافة موديل'}</h2><p className="muted">صور ومواصفات وتوفر وقواعد كمية مستقلة.</p></div><button type="button" className="close" onClick={close}>×</button></div>{error&&<div className="error">{error}</div>}
    <div className="editor-tabs">{([['basic','البيانات'],['availability','التوفر والطلب'],['images','الصور'],['specs','المواصفات'],['files','الملفات']] as const).map(([key,label])=><button type="button" key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}</button>)}</div>
    {tab==='basic'&&<div className="form-grid"><Field label="كود الموديل" value={form.modelCode} onChange={value=>change('modelCode',value)}/><Field label="الاسم بالعربية" value={form.titleAr} onChange={value=>change('titleAr',value)}/><Field label="الاسم بالإنجليزية" value={form.titleEn} onChange={value=>change('titleEn',value)}/><Field label="SKU" value={form.sku} onChange={value=>change('sku',value)}/><Field label="Barcode" value={form.barcode} onChange={value=>change('barcode',value)}/><Field label="الترتيب" type="number" value={form.sortOrder} onChange={value=>change('sortOrder',Number(value))}/><label className="field full"><span>الوصف بالعربية</span><textarea rows={4} value={form.descriptionAr} onChange={event=>change('descriptionAr',event.target.value)}/></label><label className="field full"><span>الوصف بالإنجليزية</span><textarea dir="ltr" rows={4} value={form.descriptionEn} onChange={event=>change('descriptionEn',event.target.value)}/></label></div>}
    {tab==='availability'&&<div className="form-grid"><label className="field"><span>التوفر</span><select value={form.availabilityStatus} onChange={event=>change('availabilityStatus',event.target.value)}><option value="available">متاح</option><option value="available_on_request">حسب الطلب</option><option value="out_of_stock">غير متوفر</option><option value="discontinued">متوقف</option><option value="hidden">مخفي</option></select></label><Field label="وحدة القياس" value={form.unitOfMeasure} onChange={value=>change('unitOfMeasure',value)}/><Field label="الحد الأدنى" type="number" step="0.001" value={form.minimumRequestQuantity} onChange={value=>change('minimumRequestQuantity',Number(value))}/><Field label="الحد الأعلى" type="number" step="0.001" value={form.maximumRequestQuantity} onChange={value=>change('maximumRequestQuantity',value)}/><Field label="خطوة الزيادة" type="number" step="0.001" value={form.quantityStep} onChange={value=>change('quantityStep',Number(value))}/><label className="field check"><input type="checkbox" checked={form.quoteEnabled} onChange={event=>change('quoteEnabled',event.target.checked)}/> يسمح بطلب عرض</label><label className="field check"><input type="checkbox" checked={form.isActive} onChange={event=>change('isActive',event.target.checked)}/> فعال</label><label className="field check"><input type="checkbox" checked={form.isDefault} onChange={event=>change('isDefault',event.target.checked)}/> افتراضي</label></div>}
    {tab==='images'&&<div><button type="button" className="button secondary small" onClick={()=>setImages(current=>[...current,{imageUrl:'',altTextAr:'',altTextEn:'',isPrimary:current.length===0,sortOrder:current.length}])}>إضافة صورة</button>{images.map((image,index)=><div className="row-editor image-row" key={index}>{image.imageUrl&&<img src={image.imageUrl} alt=""/>}<input placeholder="رابط الصورة" value={image.imageUrl} onChange={event=>setImages(current=>current.map((item,i)=>i===index?{...item,imageUrl:event.target.value}:item))}/><input placeholder="Alt" value={image.altTextAr} onChange={event=>setImages(current=>current.map((item,i)=>i===index?{...item,altTextAr:event.target.value}:item))}/><label><input type="radio" name="model-primary" checked={image.isPrimary} onChange={()=>setImages(current=>current.map((item,i)=>({...item,isPrimary:i===index})))}/> رئيسية</label><button type="button" className="danger-text" onClick={()=>setImages(current=>current.filter((_,i)=>i!==index))}>حذف</button></div>)}</div>}
    {tab==='specs'&&<div className="form-grid">{definitions.map(definition=>{const value=values[definition.id]??{};if(definition.value_type==='boolean')return <label className="field check" key={definition.id}><input type="checkbox" checked={Boolean(value.boolean)} onChange={event=>changeSpec(definition.id,{boolean:event.target.checked})}/>{definition.name_ar}</label>;if(definition.value_type==='option')return <label className="field" key={definition.id}><span>{definition.name_ar}</span><select value={value.optionId??''} onChange={event=>changeSpec(definition.id,{optionId:event.target.value})}><option value="">غير محدد</option>{(definition.options??[]).map((option:Row)=><option key={option.id} value={option.id}>{option.label_ar}</option>)}</select></label>;if(definition.value_type==='range')return <div className="field" key={definition.id}><span>{definition.name_ar} ({definition.unit_ar??''})</span><div className="toolbar"><input type="number" step="0.0001" value={value.number??''} onChange={event=>changeSpec(definition.id,{number:event.target.value})}/><input type="number" step="0.0001" value={value.to??''} onChange={event=>changeSpec(definition.id,{to:event.target.value})}/></div></div>;if(definition.value_type==='number')return <Field key={definition.id} label={`${definition.name_ar} ${definition.unit_ar??''}`} type="number" step="0.0001" value={value.number??''} onChange={number=>changeSpec(definition.id,{number})}/>;return <Field key={definition.id} label={`${definition.name_ar} ${definition.unit_ar??''}`} value={value.textAr??''} onChange={textAr=>changeSpec(definition.id,{textAr,textEn:textAr})}/>;})}</div>}
    {tab==='files'&&<div className="form-grid"><Field label="Datasheet PDF" type="url" value={form.datasheetUrl} onChange={value=>change('datasheetUrl',value)}/><Field label="Manual PDF" type="url" value={form.manualUrl} onChange={value=>change('manualUrl',value)}/><Field label="رابط الفيديو" type="url" value={form.videoUrl} onChange={value=>change('videoUrl',value)}/></div>}
    <div className="dialog-actions"><button className="button" disabled={saving}>{saving?'جارٍ الحفظ…':'حفظ الموديل'}</button><button type="button" className="button secondary" onClick={close}>إلغاء</button></div></form></div>;
}
