import { useCallback, useEffect, useState } from 'react';
import { api } from '../../api';
import { ModelEditorDrawer } from './ModelEditorDrawer';
type Row=Record<string,any>;
export function ModelsTable({productId,categoryId}:{productId:string;categoryId:string}){
  const[models,setModels]=useState<Row[]>([]),[editing,setEditing]=useState<Row|null>(null),[selected,setSelected]=useState<string[]>([]),[error,setError]=useState('');
  const load=useCallback(async()=>{try{setModels(await api<Row[]>(`/admin/products/${productId}/models`));}catch(value){setError((value as Error).message);}},[productId]);useEffect(()=>{void load();},[load]);
  const open=async(row:Row)=>setEditing(await api<Row>(`/admin/products/${productId}/models/${row.id}`));
  const move=async(index:number,direction:number)=>{const copy=[...models],target=index+direction;if(target<0||target>=copy.length)return;[copy[index],copy[target]]=[copy[target]!,copy[index]!];await api(`/admin/products/${productId}/models/reorder`,{method:'PATCH',body:JSON.stringify({modelIds:copy.map(row=>row.id)})});await load();};
  const duplicate=async(row:Row)=>{const modelCode=window.prompt('كود الموديل الجديد',row.model_code+'-COPY');if(!modelCode)return;await api(`/admin/products/${productId}/models/${row.id}/duplicate`,{method:'POST',body:JSON.stringify({modelCode,copyImages:true})});await load();};
  const bulk=async(isActive:boolean)=>{if(!selected.length)return;await api(`/admin/products/${productId}/models/bulk-status`,{method:'PATCH',body:JSON.stringify({modelIds:selected,isActive})});setSelected([]);await load();};
  return <><div className="section-head"><div><h3>موديلات المنتج</h3><p className="muted">كل صف جهاز مستقل بصوره ومواصفاته وقواعد كميته.</p></div><button type="button" className="button" onClick={()=>setEditing({})}>إضافة موديل</button></div>{error&&<div className="error">{error}</div>}
    {selected.length>0&&<div className="toolbar"><span>{selected.length} محدد</span><button type="button" className="button secondary small" onClick={()=>void bulk(true)}>تفعيل</button><button type="button" className="button secondary small" onClick={()=>void bulk(false)}>تعطيل</button></div>}
    <div className="table-wrap"><table><thead><tr><th></th><th>الصورة</th><th>الكود</th><th>التوفر</th><th>المواصفات</th><th>افتراضي</th><th>الحالة</th><th></th></tr></thead><tbody>{models.map((row,index)=><tr key={row.id}><td><input type="checkbox" checked={selected.includes(row.id)} onChange={event=>setSelected(current=>event.target.checked?[...current,row.id]:current.filter(id=>id!==row.id))}/></td><td>{row.primary_image_url?<img className="table-image" src={row.primary_image_url} alt=""/>:'—'}</td><td><strong>{row.model_code}</strong><div className="muted">{row.sku}</div></td><td>{row.availability_status}</td><td>{row.specification_count}</td><td>{row.is_default?'نعم':'—'}</td><td>{row.is_active?'فعال':'معطل'}</td><td><div className="mini-actions"><button type="button" onClick={()=>void open(row)}>تعديل</button><button type="button" onClick={()=>void duplicate(row)}>نسخ</button>{!row.is_default&&<button type="button" onClick={async()=>{await api(`/admin/products/${productId}/models/${row.id}/set-default`,{method:'PATCH'});await load();}}>افتراضي</button>}<button type="button" onClick={()=>void move(index,-1)}>↑</button><button type="button" onClick={()=>void move(index,1)}>↓</button><button type="button" className="danger-text" onClick={async()=>{if(window.confirm('حذف الموديل؟')){await api(`/admin/products/${productId}/models/${row.id}`,{method:'DELETE'});await load();}}}>حذف</button></div></td></tr>)}</tbody></table></div>
    {editing&&<ModelEditorDrawer productId={productId} categoryId={categoryId} model={editing} close={()=>setEditing(null)} saved={async()=>{setEditing(null);await load();}}/>}</>;
}
