import { useEffect, useState, type FormEvent } from 'react';
import { api } from '../../api';
import { ModelsTable } from './ModelsTable';
type Row=Record<string,any>;
type Image={imageUrl:string;altTextAr:string;altTextEn:string;isPrimary:boolean;sortOrder:number};
const emptyImage=():Image=>({imageUrl:'',altTextAr:'',altTextEn:'',isPrimary:false,sortOrder:0});
function flatten(rows:Row[],depth=0):Row[]{return rows.flatMap(row=>[{...row,depth},...flatten(row.children??[],depth+1)]);}
function Field({label,value,onChange,type='text',required}:{label:string;value:any;onChange:(value:string)=>void;type?:string;required?:boolean}){return <label className="field"><span>{label}</span><input type={type} required={required} value={value??''} onChange={event=>onChange(event.target.value)}/></label>;}

export function ProductEditor({product,close,saved}:{product:Row;close:()=>void;saved:()=>Promise<void>}){
  const[categories,setCategories]=useState<Row[]>([]),[brands,setBrands]=useState<Row[]>([]),[tab,setTab]=useState('overview'),[error,setError]=useState(''),[saving,setSaving]=useState(false);
  const[form,setForm]=useState(()=>({primaryCategoryId:product.primary_category_id??'',brandId:product.brand_id??'',titleAr:product.title_ar??'',titleEn:product.title_en??'',slug:product.slug??'',
    shortDescriptionAr:product.short_description_ar??'',shortDescriptionEn:product.short_description_en??'',descriptionAr:product.description_ar??'',descriptionEn:product.description_en??'',
    videoUrl:product.video_url??'',tags:(product.tags??[]).join(', '),status:product.status??'draft',quoteEnabled:product.quote_enabled??true,isFeatured:product.is_featured??false,
    sortOrder:Number(product.sort_order??0),seoTitleAr:product.seo_title_ar??'',seoTitleEn:product.seo_title_en??'',seoDescriptionAr:product.seo_description_ar??'',seoDescriptionEn:product.seo_description_en??'',
    extraCategoryIds:product.extra_category_ids??[],relatedProductIds:product.related_product_ids??[]}));
  const[images,setImages]=useState<Image[]>(()=>(product.images??[]).map((image:Row,index:number)=>({imageUrl:image.image_url,altTextAr:image.alt_text_ar??'',altTextEn:image.alt_text_en??'',isPrimary:image.is_primary??index===0,sortOrder:index})));
  useEffect(()=>{Promise.all([api<Row[]>('/admin/categories'),api<Row[]>('/admin/brands')]).then(([categoryTree,brandRows])=>{setCategories(flatten(categoryTree));setBrands(brandRows);}).catch(value=>setError((value as Error).message));},[]);
  const change=(key:string,value:any)=>setForm(current=>({...current,[key]:value}));
  const save=async(event?:FormEvent)=>{event?.preventDefault();setSaving(true);setError('');try{const nullable=(value:string)=>value.trim()?value.trim():null;const body={...form,
    brandId:form.brandId||null,titleEn:nullable(form.titleEn),shortDescriptionAr:nullable(form.shortDescriptionAr),shortDescriptionEn:nullable(form.shortDescriptionEn),descriptionAr:nullable(form.descriptionAr),descriptionEn:nullable(form.descriptionEn),videoUrl:nullable(form.videoUrl),
    seoTitleAr:nullable(form.seoTitleAr),seoTitleEn:nullable(form.seoTitleEn),seoDescriptionAr:nullable(form.seoDescriptionAr),seoDescriptionEn:nullable(form.seoDescriptionEn),tags:String(form.tags).split(',').map((value:string)=>value.trim()).filter(Boolean),
    images:images.filter(image=>image.imageUrl.trim()).map((image,index)=>({...image,sortOrder:index}))};await api(product.id?'/admin/products/'+product.id:'/admin/products',{method:product.id?'PATCH':'POST',body:JSON.stringify(body)});await saved();}
    catch(value){setError((value as Error).message);}finally{setSaving(false);}};
  const setPrimary=(index:number)=>setImages(current=>current.map((image,i)=>({...image,isPrimary:i===index})));
  return <div className="dialog-backdrop"><form className="dialog product-dialog" onSubmit={save}><div className="dialog-head"><div><h2>{product.id?'تحرير المنتج':'إنشاء منتج'}</h2><p className="muted">المنتج يحوي البيانات المشتركة، والموديلات تحوي بيانات الأجهزة الفعلية.</p></div><button type="button" className="close" onClick={close}>×</button></div>
    {error&&<div className="error">{error}</div>}<div className="editor-tabs">{([['overview','البيانات العامة'],['media','الصور العامة'],['models','الموديلات'],['seo','SEO']] as const).map(([key,label])=><button type="button" key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}</button>)}</div>
    {tab==='overview'&&<section className="editor-section"><div className="form-grid"><Field label="الاسم بالعربية" value={form.titleAr} onChange={value=>change('titleAr',value)} required/><Field label="الاسم بالإنجليزية" value={form.titleEn} onChange={value=>change('titleEn',value)}/><Field label="Slug" value={form.slug} onChange={value=>change('slug',value)} required/>
      <label className="field"><span>القسم الأساسي</span><select required value={form.primaryCategoryId} onChange={event=>change('primaryCategoryId',event.target.value)}><option value="">اختر قسمًا</option>{categories.map(row=><option key={row.id} value={row.id}>{'— '.repeat(row.depth)}{row.title_ar}</option>)}</select></label>
      <label className="field"><span>العلامة التجارية</span><select value={form.brandId} onChange={event=>change('brandId',event.target.value)}><option value="">بدون علامة</option>{brands.map(row=><option key={row.id} value={row.id}>{row.title_ar}</option>)}</select></label><Field label="وسوم (بفاصلة)" value={form.tags} onChange={value=>change('tags',value)}/><Field label="رابط الفيديو" value={form.videoUrl} onChange={value=>change('videoUrl',value)} type="url"/><Field label="الترتيب" value={form.sortOrder} onChange={value=>change('sortOrder',Number(value))} type="number"/>
      <label className="field"><span>الحالة</span><select value={form.status} onChange={event=>change('status',event.target.value)}><option value="draft">مسودة</option><option value="published">منشور</option><option value="archived">مؤرشف</option></select></label>
      <label className="field check"><input type="checkbox" checked={form.quoteEnabled} onChange={event=>change('quoteEnabled',event.target.checked)}/> طلب عرض مفعّل</label><label className="field check"><input type="checkbox" checked={form.isFeatured} onChange={event=>change('isFeatured',event.target.checked)}/> منتج مميز</label>
      <label className="field full"><span>الوصف المختصر بالعربية</span><textarea rows={2} value={form.shortDescriptionAr} onChange={event=>change('shortDescriptionAr',event.target.value)}/></label><label className="field full"><span>Short description</span><textarea dir="ltr" rows={2} value={form.shortDescriptionEn} onChange={event=>change('shortDescriptionEn',event.target.value)}/></label><label className="field full"><span>الوصف الكامل بالعربية</span><textarea rows={5} value={form.descriptionAr} onChange={event=>change('descriptionAr',event.target.value)}/></label><label className="field full"><span>Full description</span><textarea dir="ltr" rows={5} value={form.descriptionEn} onChange={event=>change('descriptionEn',event.target.value)}/></label></div></section>}
    {tab==='media'&&<section className="editor-section"><div className="section-head"><h3>صور المنتج العامة (Fallback)</h3><button type="button" className="button secondary small" onClick={()=>setImages(current=>[...current,{...emptyImage(),isPrimary:current.length===0,sortOrder:current.length}])}>إضافة صورة</button></div>{images.map((image,index)=><div className="row-editor image-row" key={index}>{image.imageUrl&&<img src={image.imageUrl} alt=""/>}<input placeholder="رابط الصورة" value={image.imageUrl} onChange={event=>setImages(current=>current.map((item,i)=>i===index?{...item,imageUrl:event.target.value}:item))}/><input placeholder="Alt عربي" value={image.altTextAr} onChange={event=>setImages(current=>current.map((item,i)=>i===index?{...item,altTextAr:event.target.value}:item))}/><label><input type="radio" name="product-primary" checked={image.isPrimary} onChange={()=>setPrimary(index)}/> رئيسية</label><button type="button" className="danger-text" onClick={()=>setImages(current=>current.filter((_,i)=>i!==index))}>حذف</button></div>)}</section>}
    {tab==='models'&&<section className="editor-section">{product.id?<ModelsTable productId={product.id} categoryId={form.primaryCategoryId}/>:<div className="notice">احفظ المنتج أولًا، ثم أضف موديلاته بصورة مستقلة.</div>}</section>}
    {tab==='seo'&&<section className="editor-section"><div className="form-grid"><Field label="عنوان SEO بالعربية" value={form.seoTitleAr} onChange={value=>change('seoTitleAr',value)}/><Field label="SEO title" value={form.seoTitleEn} onChange={value=>change('seoTitleEn',value)}/><label className="field"><span>وصف SEO بالعربية</span><textarea rows={3} value={form.seoDescriptionAr} onChange={event=>change('seoDescriptionAr',event.target.value)}/></label><label className="field"><span>SEO description</span><textarea dir="ltr" rows={3} value={form.seoDescriptionEn} onChange={event=>change('seoDescriptionEn',event.target.value)}/></label></div></section>}
    {tab!=='models'&&<div className="dialog-actions"><button className="button" disabled={saving}>{saving?'جارٍ الحفظ…':'حفظ المنتج'}</button><button type="button" className="button secondary" onClick={close}>إلغاء</button></div>}</form></div>;
}
