import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { api, download } from '../../api';
type Row=Record<string,any>;
export function CatalogImportPage({canWrite}:{canWrite:boolean}){const[file,setFile]=useState<File|null>(null),[result,setResult]=useState<Row|null>(null),[history,setHistory]=useState<Row[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(false);const load=useCallback(()=>api<Row[]>('/admin/catalog-import/history').then(setHistory).catch(()=>setHistory([])),[]);useEffect(()=>{void load();},[load]);
  const send=async(path:string)=>{if(!file)return;setLoading(true);setError('');try{const form=new FormData();form.append('file',file);setResult(await api<Row>(path,{method:'POST',body:form}));await load();}catch(value){setError((value as Error).message);}finally{setLoading(false);}};
  return <><div className="page-head"><div><h1>استيراد وتصدير الكتالوج</h1><p>Excel متعدد الأوراق أو ZIP يحتوي catalog.xlsx ومجلد images.</p></div><div className="toolbar"><button className="button secondary" onClick={()=>void download('/admin/catalog-import/template','catalog-import-template.xlsx')}>تنزيل القالب</button><button className="button secondary" onClick={()=>void download('/admin/catalog-import/export','catalog-export.xlsx')}>تصدير الكتالوج</button></div></div>{error&&<div className="error">{error}</div>}
    <div className="grid-two"><form className="panel" onSubmit={(event:FormEvent)=>{event.preventDefault();void send('/admin/catalog-import/validate');}}><h3>الملف</h3><label className="upload-drop"><input type="file" accept=".xlsx,.zip" onChange={event=>setFile(event.target.files?.[0]??null)} required/><span>{file?.name??'اختر Excel أو ZIP'}</span></label>{canWrite&&<div className="toolbar"><button className="button" disabled={loading}>Dry Run</button><button type="button" className="button secondary" disabled={loading||!result||result.errors?.length} onClick={()=>void send('/admin/catalog-import/execute')}>تنفيذ الاستيراد</button></div>}</form>
      <div className="panel"><h3>تقرير التحقق</h3>{result?<><div className="cards">{Object.entries(result.summary??{}).map(([key,value])=><div className="card metric" key={key}><span>{key}</span><strong>{String(value)}</strong></div>)}</div>{(result.errors??[]).map((issue:Row,index:number)=><div className="error" key={index}>{issue.sheet} / صف {issue.row} / {issue.field}: {issue.message}</div>)}{!(result.errors??[]).length&&<div className="success">الملف صالح للتنفيذ دون أخطاء.</div>}</>:<div className="empty">شغّل Dry Run لعرض التقرير.</div>}</div></div>
    <div className="table-wrap"><table><thead><tr><th>الملف</th><th>الحالة</th><th>الوضع</th><th>الملخص</th><th>التاريخ</th></tr></thead><tbody>{history.map(row=><tr key={row.id}><td>{row.file_name}</td><td>{row.status}</td><td>{row.dry_run?'Dry Run':'Execute'}</td><td>{JSON.stringify(row.summary)}</td><td>{new Date(row.created_at).toLocaleString('ar')}</td></tr>)}</tbody></table></div></>;
}
